; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -O0 < %s | FileCheck %s

define <32 x double> @foo(<32 x double> %LGV1) nounwind {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], -1
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbb900
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbba00
; CHECK-NEXT:    buffer_store_dword v59, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:188 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:184 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:180 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:176 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:172 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:168 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:164 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:160 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:156 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:152 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:148 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:144 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:140 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v63, off, s[0:3], s32 offset:136 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v36, v30
; CHECK-NEXT:    v_mov_b32_e32 v37, v29
; CHECK-NEXT:    v_mov_b32_e32 v38, v28
; CHECK-NEXT:    v_mov_b32_e32 v39, v27
; CHECK-NEXT:    v_mov_b32_e32 v48, v26
; CHECK-NEXT:    v_mov_b32_e32 v49, v25
; CHECK-NEXT:    v_mov_b32_e32 v50, v24
; CHECK-NEXT:    v_mov_b32_e32 v51, v23
; CHECK-NEXT:    v_mov_b32_e32 v52, v22
; CHECK-NEXT:    v_mov_b32_e32 v53, v21
; CHECK-NEXT:    v_mov_b32_e32 v54, v20
; CHECK-NEXT:    v_mov_b32_e32 v55, v19
; CHECK-NEXT:    v_mov_b32_e32 v40, v18
; CHECK-NEXT:    v_mov_b32_e32 v41, v17
; CHECK-NEXT:    v_mov_b32_e32 v42, v16
; CHECK-NEXT:    v_mov_b32_e32 v43, v15
; CHECK-NEXT:    v_mov_b32_e32 v44, v14
; CHECK-NEXT:    v_mov_b32_e32 v45, v13
; CHECK-NEXT:    v_mov_b32_e32 v46, v12
; CHECK-NEXT:    v_mov_b32_e32 v47, v11
; CHECK-NEXT:    v_mov_b32_e32 v56, v10
; CHECK-NEXT:    v_mov_b32_e32 v57, v9
; CHECK-NEXT:    v_mov_b32_e32 v60, v8
; CHECK-NEXT:    v_mov_b32_e32 v61, v7
; CHECK-NEXT:    v_mov_b32_e32 v62, v6
; CHECK-NEXT:    v_mov_b32_e32 v63, v5
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:756 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:760 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:752 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:876 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:132
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:128
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:124
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:764 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:120
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:768 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:116
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:772 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:112
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:776 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:108
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:780 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:104
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:784 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:100
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:788 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:96
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:792 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:92
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:796 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:88
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:800 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:84
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:804 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:80
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:808 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:76
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:812 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:72
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:816 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:68
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:820 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:64
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:824 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:60
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:828 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:56
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:832 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:52
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:836 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:48
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:840 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:44
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:844 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:40
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:848 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:36
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:852 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:32
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:856 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:28
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:860 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:24
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:864 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:20
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:868 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:16
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:872 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:12
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:8
; CHECK-NEXT:    ; kill: def $vgpr4 killed $vgpr4 def $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31_vgpr32_vgpr33_vgpr34_vgpr35 killed $exec
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    v_mov_b32_e32 v5, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:872 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v6, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:868 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v7, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:864 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v8, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:860 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v9, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:856 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v10, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:852 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v11, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:848 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:844 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v13, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:840 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v14, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:836 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v15, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:832 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v16, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:828 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v17, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:824 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v18, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:820 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v19, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:816 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v20, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:812 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v21, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:808 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v22, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:804 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v23, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:800 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v24, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:796 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v25, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:792 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v26, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:788 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v27, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:784 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v28, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:780 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v29, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:776 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v30, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:772 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v31, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:768 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v32, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:764 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v33, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:760 ; 4-byte Folded Reload
; CHECK-NEXT:    v_mov_b32_e32 v34, v3
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:752 ; 4-byte Folded Reload
; CHECK-NEXT:    v_mov_b32_e32 v35, v1
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:624 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:628 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:632 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:636 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:640 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:644 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:648 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:652 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:656 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:660 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:664 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:668 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:672 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:676 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:680 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:684 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:688 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:692 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:696 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:700 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:704 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:708 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:712 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:716 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:720 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:724 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:728 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:732 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v32, off, s[0:3], s32 offset:736 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v33, off, s[0:3], s32 offset:740 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v34, off, s[0:3], s32 offset:744 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v35, off, s[0:3], s32 offset:748 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:4
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31_vgpr32_vgpr33_vgpr34 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v5, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:756 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v6, v0
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:752 ; 4-byte Folded Reload
; CHECK-NEXT:    v_mov_b32_e32 v7, v63
; CHECK-NEXT:    v_mov_b32_e32 v8, v62
; CHECK-NEXT:    v_mov_b32_e32 v9, v61
; CHECK-NEXT:    v_mov_b32_e32 v10, v60
; CHECK-NEXT:    v_mov_b32_e32 v11, v57
; CHECK-NEXT:    v_mov_b32_e32 v12, v56
; CHECK-NEXT:    v_mov_b32_e32 v13, v47
; CHECK-NEXT:    v_mov_b32_e32 v14, v46
; CHECK-NEXT:    v_mov_b32_e32 v15, v45
; CHECK-NEXT:    v_mov_b32_e32 v16, v44
; CHECK-NEXT:    v_mov_b32_e32 v17, v43
; CHECK-NEXT:    v_mov_b32_e32 v18, v42
; CHECK-NEXT:    v_mov_b32_e32 v19, v41
; CHECK-NEXT:    v_mov_b32_e32 v20, v40
; CHECK-NEXT:    v_mov_b32_e32 v21, v55
; CHECK-NEXT:    v_mov_b32_e32 v22, v54
; CHECK-NEXT:    v_mov_b32_e32 v23, v53
; CHECK-NEXT:    v_mov_b32_e32 v24, v52
; CHECK-NEXT:    v_mov_b32_e32 v25, v51
; CHECK-NEXT:    v_mov_b32_e32 v26, v50
; CHECK-NEXT:    v_mov_b32_e32 v27, v49
; CHECK-NEXT:    v_mov_b32_e32 v28, v48
; CHECK-NEXT:    v_mov_b32_e32 v29, v39
; CHECK-NEXT:    v_mov_b32_e32 v30, v38
; CHECK-NEXT:    v_mov_b32_e32 v31, v37
; CHECK-NEXT:    v_mov_b32_e32 v32, v36
; CHECK-NEXT:    v_mov_b32_e32 v33, v35
; CHECK-NEXT:    v_mov_b32_e32 v34, v1
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:368 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:372 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:376 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:380 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:384 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:388 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:392 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:396 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:400 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:404 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:408 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:412 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:416 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:420 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:424 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:428 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:432 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:436 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:440 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:444 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:448 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:452 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:456 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:460 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:464 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:468 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:472 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:476 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:480 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v32, off, s[0:3], s32 offset:484 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v33, off, s[0:3], s32 offset:488 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v34, off, s[0:3], s32 offset:492 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:624 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:628 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:632 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:636 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:640 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:644 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:648 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:652 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:656 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:660 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:664 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:668 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:672 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:676 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:680 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:684 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:688 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:692 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:696 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:700 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:704 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:708 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:712 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:716 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:720 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:724 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:728 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:732 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:736 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:740 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:744 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:748 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:368 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:372 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:376 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:380 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:384 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:388 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:392 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:396 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:400 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:404 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:408 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:412 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:416 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:420 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:424 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:428 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:432 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:436 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:440 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:444 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:448 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:452 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:456 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:460 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:464 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:468 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:472 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:476 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:480 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:484 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:488 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:492 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Spill
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:232 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:236 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    ; implicit-def: $vgpr58 : SGPR spill to VGPR lane
; CHECK-NEXT:    v_writelane_b32 v58, s4, 0
; CHECK-NEXT:    v_writelane_b32 v58, s5, 1
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:224 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:228 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 2
; CHECK-NEXT:    v_writelane_b32 v58, s7, 3
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_281
; CHECK-NEXT:    s_branch .LBB0_283
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1152 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1156 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:232 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:236 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(4)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 4
; CHECK-NEXT:    v_writelane_b32 v58, s5, 5
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[2:3], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v2, v3, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v1, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[6:7]
; CHECK-NEXT:    ; implicit-def: $sgpr45
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr44
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr43
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr42
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr41
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr40
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr29
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr28
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr27
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr26
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr25
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr24
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr23
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr22
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr21
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr20
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr19
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr18
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr17
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr16
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr15
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr14
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr13
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr12
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr11
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr10
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr9
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr8
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr7
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr6
; CHECK-NEXT:    ; implicit-def: $sgpr46
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v32
; CHECK-NEXT:    v_mov_b32_e32 v2, s45
; CHECK-NEXT:    v_mov_b32_e32 v3, s44
; CHECK-NEXT:    v_mov_b32_e32 v4, s43
; CHECK-NEXT:    v_mov_b32_e32 v5, s42
; CHECK-NEXT:    v_mov_b32_e32 v6, s41
; CHECK-NEXT:    v_mov_b32_e32 v7, s40
; CHECK-NEXT:    v_mov_b32_e32 v8, s29
; CHECK-NEXT:    v_mov_b32_e32 v9, s28
; CHECK-NEXT:    v_mov_b32_e32 v10, s27
; CHECK-NEXT:    v_mov_b32_e32 v11, s26
; CHECK-NEXT:    v_mov_b32_e32 v12, s25
; CHECK-NEXT:    v_mov_b32_e32 v13, s24
; CHECK-NEXT:    v_mov_b32_e32 v14, s23
; CHECK-NEXT:    v_mov_b32_e32 v15, s22
; CHECK-NEXT:    v_mov_b32_e32 v16, s21
; CHECK-NEXT:    v_mov_b32_e32 v17, s20
; CHECK-NEXT:    v_mov_b32_e32 v18, s19
; CHECK-NEXT:    v_mov_b32_e32 v19, s18
; CHECK-NEXT:    v_mov_b32_e32 v20, s17
; CHECK-NEXT:    v_mov_b32_e32 v21, s16
; CHECK-NEXT:    v_mov_b32_e32 v22, s15
; CHECK-NEXT:    v_mov_b32_e32 v23, s14
; CHECK-NEXT:    v_mov_b32_e32 v24, s13
; CHECK-NEXT:    v_mov_b32_e32 v25, s12
; CHECK-NEXT:    v_mov_b32_e32 v26, s11
; CHECK-NEXT:    v_mov_b32_e32 v27, s10
; CHECK-NEXT:    v_mov_b32_e32 v28, s9
; CHECK-NEXT:    v_mov_b32_e32 v29, s8
; CHECK-NEXT:    v_mov_b32_e32 v30, s7
; CHECK-NEXT:    v_mov_b32_e32 v31, s6
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1024 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1028 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1032 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1036 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:1040 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:1044 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:1048 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:1052 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:1056 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:1060 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:1064 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:1068 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:1072 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:1076 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:1080 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:1084 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:1088 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:1092 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:1096 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:1100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:1104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:1108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:1112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:1116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:1120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:1124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:1128 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:1132 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:1136 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:1140 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:1144 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:1148 ; 4-byte Folded Spill
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1024 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1028 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:1032 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:1036 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:1040 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:1044 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1048 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1052 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:1056 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:1060 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:1064 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:1068 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:1072 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:1076 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:1080 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:1084 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:1088 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:1092 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:1096 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:1100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:1104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:1108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:1112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:1116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:1120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:1124 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1128 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1132 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1136 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1140 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1144 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1148 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:896 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:900 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:904 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:908 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:912 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:916 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:920 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:924 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:928 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:932 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:936 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:940 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:944 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:948 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:952 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:956 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:960 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:964 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:968 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:972 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:976 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:980 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:984 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:988 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:992 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:996 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:1000 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:1004 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:1008 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:1012 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:1016 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:1020 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v6
; CHECK-NEXT:    v_mov_b32_e32 v0, v5
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:888 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:892 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:880 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:884 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 6
; CHECK-NEXT:    v_writelane_b32 v58, s7, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_273
; CHECK-NEXT:    s_branch .LBB0_275
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:896 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:900 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:904 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:908 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:912 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:916 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:920 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:924 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:928 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:932 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:936 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:940 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:944 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:948 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:952 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:956 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:960 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:964 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:968 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:972 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:976 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:980 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:984 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:988 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:992 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:996 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1000 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1004 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1008 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1012 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1016 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1020 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:1560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:1564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:888 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:892 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 8
; CHECK-NEXT:    v_writelane_b32 v58, s5, 9
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v2, v33
; CHECK-NEXT:    v_mov_b32_e32 v3, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1432 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1436 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1440 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1444 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:1448 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:1452 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:1456 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:1460 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:1464 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:1468 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:1472 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:1476 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:1480 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:1484 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:1488 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:1492 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:1496 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:1500 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:1504 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:1508 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:1512 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:1516 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:1520 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:1524 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:1528 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:1532 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:1536 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:1540 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:1544 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:1548 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:1552 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:1556 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:1312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:1316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:1320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:1324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:1336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:1340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:1344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:1348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:1352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:1356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:1360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:1364 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:1368 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:1372 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:1376 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:1380 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:1384 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:1388 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:1392 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:1396 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:1400 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:1404 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1408 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1412 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1416 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1420 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1424 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1428 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1176 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1180 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1184 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1188 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:1192 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:1196 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:1200 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:1204 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:1208 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:1212 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:1216 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:1220 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:1224 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:1228 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:1232 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:1236 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:1240 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:1244 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:1248 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:1252 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:1256 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:1260 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:1264 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:1268 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:1272 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:1276 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:1280 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:1284 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:1288 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:1292 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:1296 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:1300 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v8
; CHECK-NEXT:    v_mov_b32_e32 v0, v7
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1168 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1172 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1160 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1164 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 10
; CHECK-NEXT:    v_writelane_b32 v58, s7, 11
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_265
; CHECK-NEXT:    s_branch .LBB0_267
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1432 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1436 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:1440 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:1444 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:1448 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:1452 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1456 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1460 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:1464 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:1468 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:1472 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:1476 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:1480 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:1484 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:1488 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:1492 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:1496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:1500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:1504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:1508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:1512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:1516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:1520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:1524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:1528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:1532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:1840 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:1844 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:1168 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:1172 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 12
; CHECK-NEXT:    v_writelane_b32 v58, s5, 13
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v4, v33
; CHECK-NEXT:    v_mov_b32_e32 v5, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1712 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1716 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1720 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1724 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:1728 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:1732 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:1736 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:1740 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:1744 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:1748 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:1752 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:1756 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:1760 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:1764 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:1768 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:1772 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:1776 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:1780 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:1784 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:1788 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:1792 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:1796 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:1800 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:1804 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:1808 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:1812 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:1816 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:1820 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:1824 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:1828 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:1832 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:1836 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1176 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1180 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:1184 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:1188 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:1192 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:1196 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1200 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1204 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:1208 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:1212 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:1216 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:1220 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:1224 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:1228 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:1232 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:1236 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:1240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:1244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:1248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:1252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:1256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:1260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:1264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:1268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:1272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:1276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1300 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1584 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1588 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1592 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1596 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:1600 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:1604 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:1608 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:1612 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:1616 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:1620 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:1624 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:1628 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:1632 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:1636 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:1640 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:1644 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:1648 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:1652 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:1656 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:1660 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:1664 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:1668 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:1672 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:1676 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:1680 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:1684 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:1688 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:1692 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:1696 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:1700 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:1704 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:1708 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v10
; CHECK-NEXT:    v_mov_b32_e32 v0, v9
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1576 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1580 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1568 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1572 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 14
; CHECK-NEXT:    v_writelane_b32 v58, s7, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_257
; CHECK-NEXT:    s_branch .LBB0_259
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1712 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1716 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:1720 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:1724 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:1728 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:1732 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1736 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1740 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:1744 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:1748 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:1752 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:1756 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:1760 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:1764 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:1768 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:1772 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:1776 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:1780 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:1784 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:1788 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:1792 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:1796 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:1800 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:1804 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:1808 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:1812 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1816 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1820 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1824 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1828 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1832 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1836 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:2120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:2124 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:1576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:1580 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 16
; CHECK-NEXT:    v_writelane_b32 v58, s5, 17
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v6, v33
; CHECK-NEXT:    v_mov_b32_e32 v7, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1992 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1996 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2000 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2004 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:2008 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:2012 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:2016 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:2020 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:2024 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:2028 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:2032 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:2036 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:2040 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:2044 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:2048 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:2052 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:2056 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:2060 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:2064 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:2068 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:2072 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:2076 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:2080 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:2084 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:2088 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:2092 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:2096 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:2100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:2104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:2108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:2112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:2116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:1592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:1596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:1600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:1604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:1616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:1620 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:1624 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:1628 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:1632 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:1636 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:1640 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:1644 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:1648 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:1652 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:1656 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:1660 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:1664 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:1668 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:1672 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:1676 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:1680 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:1684 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1688 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1692 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1696 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1700 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1704 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1708 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1864 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1868 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1872 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1876 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:1880 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:1884 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:1888 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:1892 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:1896 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:1900 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:1904 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:1908 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:1912 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:1916 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:1920 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:1924 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:1928 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:1932 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:1936 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:1940 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:1944 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:1948 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:1952 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:1956 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:1960 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:1964 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:1968 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:1972 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:1976 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:1980 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:1984 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:1988 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v12
; CHECK-NEXT:    v_mov_b32_e32 v0, v11
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1856 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1860 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:1848 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:1852 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 18
; CHECK-NEXT:    v_writelane_b32 v58, s7, 19
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_249
; CHECK-NEXT:    s_branch .LBB0_251
; CHECK-NEXT:  .LBB0_5:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1992 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1996 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2000 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2004 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:2008 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:2012 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2016 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2020 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:2024 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:2028 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:2032 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:2036 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:2040 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:2044 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:2048 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:2052 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:2056 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:2060 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:2064 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:2068 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:2072 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:2076 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:2080 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:2084 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:2088 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:2092 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:2096 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:2100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:2104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:2108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:2112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:2116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:2400 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:2404 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:1856 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:1860 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 20
; CHECK-NEXT:    v_writelane_b32 v58, s5, 21
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v8, v33
; CHECK-NEXT:    v_mov_b32_e32 v9, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2272 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2276 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2280 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2284 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:2288 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:2292 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:2296 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:2300 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:2304 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:2308 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:2312 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:2316 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:2320 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:2324 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:2328 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:2332 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:2336 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:2340 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:2344 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:2348 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:2352 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:2356 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:2360 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:2364 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:2368 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:2372 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:2376 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:2380 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:2384 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:2388 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:2392 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:2396 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:1864 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:1868 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:1872 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:1876 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:1880 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:1884 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1888 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1892 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:1896 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:1900 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:1904 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:1908 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:1912 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:1916 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:1920 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:1924 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:1928 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:1932 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:1936 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:1940 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:1944 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:1948 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:1952 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:1956 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:1960 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:1964 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:1968 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:1972 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:1976 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:1980 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:1984 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:1988 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2144 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2148 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2152 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2156 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:2160 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:2164 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:2168 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:2172 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:2176 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:2180 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:2184 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:2188 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:2192 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:2196 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:2200 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:2204 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:2208 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:2212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:2216 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:2220 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:2224 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:2228 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:2232 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:2236 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:2240 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:2244 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:2248 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:2252 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:2256 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:2260 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:2264 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:2268 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v14
; CHECK-NEXT:    v_mov_b32_e32 v0, v13
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2136 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2140 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2128 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2132 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 22
; CHECK-NEXT:    v_writelane_b32 v58, s7, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_241
; CHECK-NEXT:    s_branch .LBB0_243
; CHECK-NEXT:  .LBB0_6:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:2272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:2276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:2288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:2292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:2304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:2308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:2312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:2316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:2320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:2324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:2328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:2332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:2336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:2340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:2344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:2348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:2352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:2356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:2360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:2364 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:2368 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:2372 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:2376 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:2380 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:2384 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:2388 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:2392 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:2396 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:2680 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:2684 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:2136 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:2140 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 24
; CHECK-NEXT:    v_writelane_b32 v58, s5, 25
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v10, v33
; CHECK-NEXT:    v_mov_b32_e32 v11, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2552 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2556 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2560 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2564 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:2568 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:2572 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:2576 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:2580 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:2584 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:2588 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:2592 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:2596 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:2600 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:2604 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:2608 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:2612 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:2616 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:2620 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:2624 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:2628 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:2632 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:2636 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:2640 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:2644 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:2648 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:2652 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:2656 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:2660 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:2664 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:2668 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:2672 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:2676 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:2144 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:2148 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2152 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2156 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:2160 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:2164 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2168 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2172 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:2176 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:2180 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:2184 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:2188 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:2192 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:2196 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:2200 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:2204 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:2208 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:2212 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:2216 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:2220 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:2224 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:2228 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:2232 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:2236 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:2240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:2244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:2248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:2252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:2256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:2260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:2264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:2268 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2424 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2428 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2432 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2436 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:2440 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:2444 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:2448 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:2452 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:2456 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:2460 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:2464 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:2468 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:2472 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:2476 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:2480 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:2484 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:2488 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:2492 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:2496 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:2500 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:2504 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:2508 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:2512 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:2516 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:2520 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:2524 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:2528 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:2532 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:2536 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:2540 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:2544 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:2548 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v16
; CHECK-NEXT:    v_mov_b32_e32 v0, v15
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2416 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2420 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2408 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2412 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 26
; CHECK-NEXT:    v_writelane_b32 v58, s7, 27
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_233
; CHECK-NEXT:    s_branch .LBB0_235
; CHECK-NEXT:  .LBB0_7:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:2552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:2556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:2568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:2572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:2584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:2588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:2592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:2596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:2600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:2604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:2608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:2612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:2616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:2620 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:2624 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:2628 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:2632 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:2636 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:2640 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:2644 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:2648 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:2652 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:2656 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:2660 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:2664 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:2668 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:2672 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:2676 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:2960 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:2964 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:2416 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:2420 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 28
; CHECK-NEXT:    v_writelane_b32 v58, s5, 29
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v12, v33
; CHECK-NEXT:    v_mov_b32_e32 v13, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2832 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2836 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2840 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2844 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:2848 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:2852 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:2856 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:2860 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:2864 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:2868 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:2872 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:2876 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:2880 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:2884 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:2888 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:2892 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:2896 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:2900 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:2904 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:2908 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:2912 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:2916 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:2920 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:2924 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:2928 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:2932 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:2936 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:2940 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:2944 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:2948 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:2952 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:2956 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:2424 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:2428 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2432 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2436 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:2440 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:2444 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2448 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2452 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:2456 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:2460 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:2464 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:2468 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:2472 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:2476 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:2480 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:2484 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:2488 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:2492 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:2496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:2500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:2504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:2508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:2512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:2516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:2520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:2524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:2528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:2532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:2536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:2540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:2544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:2548 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2704 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2708 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2712 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2716 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:2720 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:2724 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:2728 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:2732 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:2736 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:2740 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:2744 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:2748 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:2752 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:2756 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:2760 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:2764 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:2768 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:2772 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:2776 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:2780 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:2784 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:2788 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:2792 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:2796 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:2800 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:2804 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:2808 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:2812 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:2816 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:2820 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:2824 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:2828 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v18
; CHECK-NEXT:    v_mov_b32_e32 v0, v17
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2696 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2700 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2688 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2692 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 30
; CHECK-NEXT:    v_writelane_b32 v58, s7, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_225
; CHECK-NEXT:    s_branch .LBB0_227
; CHECK-NEXT:  .LBB0_8:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:2832 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:2836 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2840 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2844 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:2848 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:2852 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2856 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2860 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:2864 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:2868 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:2872 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:2876 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:2880 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:2884 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:2888 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:2892 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:2896 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:2900 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:2904 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:2908 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:2912 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:2916 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:2920 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:2924 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:2928 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:2932 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:2936 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:2940 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:2944 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:2948 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:2952 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:2956 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:3240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:3244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:2696 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:2700 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 32
; CHECK-NEXT:    v_writelane_b32 v58, s5, 33
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v14, v33
; CHECK-NEXT:    v_mov_b32_e32 v15, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3128 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3132 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3136 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3140 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3144 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3148 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3152 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3156 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:3160 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:3164 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:3168 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:3172 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:3176 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:3180 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:3184 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:3188 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:3192 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:3196 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:3200 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:3204 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:3208 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:3212 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:3216 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:3220 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:3224 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:3228 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:3232 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:3236 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:2704 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:2708 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2712 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2716 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:2720 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:2724 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2728 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2732 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:2736 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:2740 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:2744 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:2748 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:2752 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:2756 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:2760 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:2764 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:2768 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:2772 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:2776 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:2780 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:2784 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:2788 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:2792 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:2796 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:2800 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:2804 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:2808 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:2812 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:2816 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:2820 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:2824 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:2828 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2984 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2988 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2992 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2996 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3000 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3004 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3008 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3012 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3016 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3020 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3024 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3028 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:3032 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:3036 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:3040 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:3044 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:3048 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:3052 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:3056 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:3060 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:3064 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:3068 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:3072 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:3076 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:3080 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:3084 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:3088 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:3092 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:3096 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:3100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:3104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:3108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v20
; CHECK-NEXT:    v_mov_b32_e32 v0, v19
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2976 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2980 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:2968 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:2972 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 34
; CHECK-NEXT:    v_writelane_b32 v58, s7, 35
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_217
; CHECK-NEXT:    s_branch .LBB0_219
; CHECK-NEXT:  .LBB0_9:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:3112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:3116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:3120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:3124 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3128 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3132 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3136 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3140 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3144 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3148 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3152 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3156 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:3160 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:3164 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:3168 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:3172 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:3176 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:3180 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:3184 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:3188 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:3192 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:3196 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:3200 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:3204 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:3208 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:3212 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:3216 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:3220 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:3224 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:3228 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:3232 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:3236 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:3520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:3524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:2976 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:2980 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 36
; CHECK-NEXT:    v_writelane_b32 v58, s5, 37
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v16, v33
; CHECK-NEXT:    v_mov_b32_e32 v17, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3392 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3396 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3400 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3404 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3408 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3412 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3416 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3420 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3424 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3428 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3432 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3436 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:3440 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:3444 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:3448 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:3452 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:3456 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:3460 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:3464 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:3468 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:3472 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:3476 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:3480 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:3484 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:3488 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:3492 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:3496 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:3500 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:3504 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:3508 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:3512 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:3516 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:2984 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:2988 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:2992 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:2996 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3000 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3004 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3008 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3012 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3016 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3020 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3024 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3028 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:3032 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:3036 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:3040 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:3044 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:3048 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:3052 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:3056 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:3060 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:3064 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:3068 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:3072 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:3076 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:3080 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:3084 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:3088 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:3092 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:3096 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:3100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:3104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:3108 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3264 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3268 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3272 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3276 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3280 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3284 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3288 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3292 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3296 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3300 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3304 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3308 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:3312 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:3316 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:3320 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:3324 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:3328 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:3332 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:3336 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:3340 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:3344 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:3348 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:3352 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:3356 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:3360 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:3364 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:3368 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:3372 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:3376 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:3380 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:3384 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:3388 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(12)
; CHECK-NEXT:    v_mov_b32_e32 v2, v22
; CHECK-NEXT:    v_mov_b32_e32 v0, v21
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3256 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3260 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3248 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3252 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 38
; CHECK-NEXT:    v_writelane_b32 v58, s7, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_209
; CHECK-NEXT:    s_branch .LBB0_211
; CHECK-NEXT:  .LBB0_10:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:3392 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:3396 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:3400 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:3404 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3408 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3412 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3416 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3420 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3424 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3428 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3432 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3436 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:3440 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:3444 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:3448 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:3452 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:3456 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:3460 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:3464 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:3468 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:3472 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:3476 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:3480 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:3484 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:3488 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:3492 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:3496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:3500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:3504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:3508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:3512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:3516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:3800 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:3804 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:3256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:3260 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 40
; CHECK-NEXT:    v_writelane_b32 v58, s5, 41
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v18, v33
; CHECK-NEXT:    v_mov_b32_e32 v19, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3672 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3676 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3680 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3684 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3688 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3692 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3696 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3700 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3704 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3708 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3712 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3716 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:3720 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:3724 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:3728 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:3732 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:3736 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:3740 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:3744 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:3748 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:3752 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:3756 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:3760 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:3764 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:3768 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:3772 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:3776 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:3780 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:3784 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:3788 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:3792 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:3796 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:3264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:3268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:3272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:3276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:3312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:3316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:3320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:3324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:3328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:3332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:3336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:3340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:3344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:3348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:3352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:3356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:3360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:3364 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:3368 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:3372 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:3376 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:3380 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:3384 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:3388 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3544 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3548 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3552 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3556 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3560 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3564 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3568 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3572 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3576 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3580 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3584 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3588 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:3592 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:3596 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:3600 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:3604 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:3608 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:3612 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:3616 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:3620 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:3624 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:3628 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:3632 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:3636 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:3640 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:3644 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:3648 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:3652 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:3656 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:3660 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:3664 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:3668 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(10)
; CHECK-NEXT:    v_mov_b32_e32 v2, v24
; CHECK-NEXT:    v_mov_b32_e32 v0, v23
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3536 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3540 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3528 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3532 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 42
; CHECK-NEXT:    v_writelane_b32 v58, s7, 43
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_201
; CHECK-NEXT:    s_branch .LBB0_203
; CHECK-NEXT:  .LBB0_11:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:3672 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:3676 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:3680 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:3684 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3688 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3692 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3696 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3700 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3704 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3708 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3712 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3716 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:3720 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:3724 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:3728 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:3732 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:3736 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:3740 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:3744 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:3748 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:3752 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:3756 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:3760 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:3764 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:3768 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:3772 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:3776 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:3780 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:3784 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:3788 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:3792 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:3796 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:4080 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:4084 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:3536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:3540 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 44
; CHECK-NEXT:    v_writelane_b32 v58, s5, 45
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v20, v33
; CHECK-NEXT:    v_mov_b32_e32 v21, v32
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3952 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3956 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3960 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3964 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3968 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3972 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3976 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3980 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3984 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3988 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3992 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3996 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:4000 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:4004 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:4008 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:4012 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:4016 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:4020 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:4024 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:4028 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:4032 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:4036 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:4040 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:4044 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:4048 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:4052 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:4056 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:4060 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:4064 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:4068 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:4072 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:4076 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:3544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:3548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:3552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:3556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:3592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:3596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:3600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:3604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:3608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:3612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:3616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:3620 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:3624 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:3628 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:3632 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:3636 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:3640 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:3644 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:3648 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:3652 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:3656 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:3660 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:3664 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:3668 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3824 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3828 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3832 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3836 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:3840 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:3844 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:3848 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:3852 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:3856 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:3860 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:3864 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:3868 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:3872 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:3876 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:3880 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:3884 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:3888 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:3892 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:3896 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:3900 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:3904 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:3908 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:3912 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:3916 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:3920 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:3924 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:3928 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:3932 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:3936 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:3940 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:3944 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:3948 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(8)
; CHECK-NEXT:    v_mov_b32_e32 v2, v26
; CHECK-NEXT:    v_mov_b32_e32 v0, v25
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3816 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3820 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:3808 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:3812 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 46
; CHECK-NEXT:    v_writelane_b32 v58, s7, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_193
; CHECK-NEXT:    s_branch .LBB0_195
; CHECK-NEXT:  .LBB0_12:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:3952 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:3956 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:3960 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:3964 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3968 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3972 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3976 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3980 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3984 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3988 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3992 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3996 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:4000 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:4004 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:4008 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:4012 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:4016 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:4020 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:4024 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:4028 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:4032 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:4036 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:4040 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:4044 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:4048 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:4052 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:4056 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:4060 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:4064 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:4068 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:4072 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:4076 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x44200
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:3816 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:3820 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 48
; CHECK-NEXT:    v_writelane_b32 v58, s5, 49
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v22, v33
; CHECK-NEXT:    v_mov_b32_e32 v23, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x42200
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:3824 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:3828 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:3832 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:3836 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:3840 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:3844 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3848 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3852 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:3856 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:3860 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:3864 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:3868 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:3872 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:3876 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:3880 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:3884 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:3888 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:3892 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:3896 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:3900 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:3904 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:3908 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:3912 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:3916 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:3920 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:3924 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:3928 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:3932 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:3936 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:3940 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:3944 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:3948 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x40200
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(6)
; CHECK-NEXT:    v_mov_b32_e32 v2, v28
; CHECK-NEXT:    v_mov_b32_e32 v0, v27
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x40000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:4088 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:4092 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 50
; CHECK-NEXT:    v_writelane_b32 v58, s7, 51
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_185
; CHECK-NEXT:    s_branch .LBB0_187
; CHECK-NEXT:  .LBB0_13:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x42200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x48800
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x40000
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 52
; CHECK-NEXT:    v_writelane_b32 v58, s5, 53
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v24, v33
; CHECK-NEXT:    v_mov_b32_e32 v25, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x46800
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x40200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x44800
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(4)
; CHECK-NEXT:    v_mov_b32_e32 v2, v30
; CHECK-NEXT:    v_mov_b32_e32 v0, v29
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x44600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x44400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 54
; CHECK-NEXT:    v_writelane_b32 v58, s7, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_177
; CHECK-NEXT:    s_branch .LBB0_179
; CHECK-NEXT:  .LBB0_14:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x46800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x4ce00
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x44600
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 56
; CHECK-NEXT:    v_writelane_b32 v58, s5, 57
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v26, v33
; CHECK-NEXT:    v_mov_b32_e32 v27, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x4ae00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x44800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x48e00
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    v_mov_b32_e32 v2, v32
; CHECK-NEXT:    v_mov_b32_e32 v0, v31
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x48c00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x48a00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 58
; CHECK-NEXT:    v_writelane_b32 v58, s7, 59
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_169
; CHECK-NEXT:    s_branch .LBB0_171
; CHECK-NEXT:  .LBB0_15:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x4ae00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x51400
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x48c00
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 60
; CHECK-NEXT:    v_writelane_b32 v58, s5, 61
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v28, v33
; CHECK-NEXT:    v_mov_b32_e32 v29, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x4f400
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x48e00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x4d400
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v2, v34
; CHECK-NEXT:    v_mov_b32_e32 v0, v33
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x4d200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x4d000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 62
; CHECK-NEXT:    v_writelane_b32 v58, s7, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_161
; CHECK-NEXT:    s_branch .LBB0_163
; CHECK-NEXT:  .LBB0_16:
; CHECK-NEXT:    s_add_i32 s4, s32, 0x4f400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x55a00
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x4d200
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    ; implicit-def: $vgpr58 : SGPR spill to VGPR lane
; CHECK-NEXT:    v_writelane_b32 v58, s4, 0
; CHECK-NEXT:    v_writelane_b32 v58, s5, 1
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v30, v33
; CHECK-NEXT:    v_mov_b32_e32 v31, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x53a00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x4d400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x51a00
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v4
; CHECK-NEXT:    v_mov_b32_e32 v0, v3
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x51800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x51600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 2
; CHECK-NEXT:    v_writelane_b32 v58, s7, 3
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_153
; CHECK-NEXT:    s_branch .LBB0_155
; CHECK-NEXT:  .LBB0_17:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x51a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x5a000
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x51800
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 4
; CHECK-NEXT:    v_writelane_b32 v58, s5, 5
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v0, v33
; CHECK-NEXT:    v_mov_b32_e32 v1, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x58000
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x53a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x56000
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v6
; CHECK-NEXT:    v_mov_b32_e32 v0, v5
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x55e00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x55c00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 6
; CHECK-NEXT:    v_writelane_b32 v58, s7, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_145
; CHECK-NEXT:    s_branch .LBB0_147
; CHECK-NEXT:  .LBB0_18:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x58000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x5e600
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x55e00
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 8
; CHECK-NEXT:    v_writelane_b32 v58, s5, 9
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v2, v33
; CHECK-NEXT:    v_mov_b32_e32 v3, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5c600
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x56000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5a600
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v8
; CHECK-NEXT:    v_mov_b32_e32 v0, v7
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5a400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5a200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 10
; CHECK-NEXT:    v_writelane_b32 v58, s7, 11
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_137
; CHECK-NEXT:    s_branch .LBB0_139
; CHECK-NEXT:  .LBB0_19:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x5c600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x62c00
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x5a400
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 12
; CHECK-NEXT:    v_writelane_b32 v58, s5, 13
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v4, v33
; CHECK-NEXT:    v_mov_b32_e32 v5, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x60c00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5a600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5ec00
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v10
; CHECK-NEXT:    v_mov_b32_e32 v0, v9
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5ea00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5e800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 14
; CHECK-NEXT:    v_writelane_b32 v58, s7, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_129
; CHECK-NEXT:    s_branch .LBB0_131
; CHECK-NEXT:  .LBB0_20:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x60c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x67200
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x5ea00
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 16
; CHECK-NEXT:    v_writelane_b32 v58, s5, 17
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v6, v33
; CHECK-NEXT:    v_mov_b32_e32 v7, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x65200
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5ec00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x63200
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v12
; CHECK-NEXT:    v_mov_b32_e32 v0, v11
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x63000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x62e00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 18
; CHECK-NEXT:    v_writelane_b32 v58, s7, 19
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_121
; CHECK-NEXT:    s_branch .LBB0_123
; CHECK-NEXT:  .LBB0_21:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x65200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x6b800
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x63000
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 20
; CHECK-NEXT:    v_writelane_b32 v58, s5, 21
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v8, v33
; CHECK-NEXT:    v_mov_b32_e32 v9, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x69800
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x63200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x67800
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v14
; CHECK-NEXT:    v_mov_b32_e32 v0, v13
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x67600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x67400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 22
; CHECK-NEXT:    v_writelane_b32 v58, s7, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_113
; CHECK-NEXT:    s_branch .LBB0_115
; CHECK-NEXT:  .LBB0_22:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x69800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x6fe00
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x67600
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 24
; CHECK-NEXT:    v_writelane_b32 v58, s5, 25
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v10, v33
; CHECK-NEXT:    v_mov_b32_e32 v11, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x6de00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x67800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x6be00
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v16
; CHECK-NEXT:    v_mov_b32_e32 v0, v15
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x6bc00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x6ba00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 26
; CHECK-NEXT:    v_writelane_b32 v58, s7, 27
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_105
; CHECK-NEXT:    s_branch .LBB0_107
; CHECK-NEXT:  .LBB0_23:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x6de00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x74400
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x6bc00
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 28
; CHECK-NEXT:    v_writelane_b32 v58, s5, 29
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v12, v33
; CHECK-NEXT:    v_mov_b32_e32 v13, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x72400
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x6be00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x70400
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v18
; CHECK-NEXT:    v_mov_b32_e32 v0, v17
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x70200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x70000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 30
; CHECK-NEXT:    v_writelane_b32 v58, s7, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_97
; CHECK-NEXT:    s_branch .LBB0_99
; CHECK-NEXT:  .LBB0_24:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x72400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x78a00
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x70200
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 32
; CHECK-NEXT:    v_writelane_b32 v58, s5, 33
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v14, v33
; CHECK-NEXT:    v_mov_b32_e32 v15, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x76a00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x70400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x74a00
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_mov_b32_e32 v2, v20
; CHECK-NEXT:    v_mov_b32_e32 v0, v19
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x74800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x74600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 34
; CHECK-NEXT:    v_writelane_b32 v58, s7, 35
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_89
; CHECK-NEXT:    s_branch .LBB0_91
; CHECK-NEXT:  .LBB0_25:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x76a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x7d000
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x74800
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 36
; CHECK-NEXT:    v_writelane_b32 v58, s5, 37
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v16, v33
; CHECK-NEXT:    v_mov_b32_e32 v17, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x7b000
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x74a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x79000
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(12)
; CHECK-NEXT:    v_mov_b32_e32 v2, v22
; CHECK-NEXT:    v_mov_b32_e32 v0, v21
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x78e00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x78c00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 38
; CHECK-NEXT:    v_writelane_b32 v58, s7, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_81
; CHECK-NEXT:    s_branch .LBB0_83
; CHECK-NEXT:  .LBB0_26:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x7b000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x81600
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x78e00
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 40
; CHECK-NEXT:    v_writelane_b32 v58, s5, 41
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v18, v33
; CHECK-NEXT:    v_mov_b32_e32 v19, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x7f600
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x79000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x7d600
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(10)
; CHECK-NEXT:    v_mov_b32_e32 v2, v24
; CHECK-NEXT:    v_mov_b32_e32 v0, v23
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x7d400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x7d200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 42
; CHECK-NEXT:    v_writelane_b32 v58, s7, 43
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_73
; CHECK-NEXT:    s_branch .LBB0_75
; CHECK-NEXT:  .LBB0_27:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x7f600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x85c00
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x7d400
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 44
; CHECK-NEXT:    v_writelane_b32 v58, s5, 45
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v20, v33
; CHECK-NEXT:    v_mov_b32_e32 v21, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x83c00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x7d600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x81c00
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(8)
; CHECK-NEXT:    v_mov_b32_e32 v2, v26
; CHECK-NEXT:    v_mov_b32_e32 v0, v25
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x81a00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x81800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 46
; CHECK-NEXT:    v_writelane_b32 v58, s7, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_65
; CHECK-NEXT:    s_branch .LBB0_67
; CHECK-NEXT:  .LBB0_28:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x83c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x8a200
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x81a00
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 48
; CHECK-NEXT:    v_writelane_b32 v58, s5, 49
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v22, v33
; CHECK-NEXT:    v_mov_b32_e32 v23, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x88200
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x81c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x86200
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(6)
; CHECK-NEXT:    v_mov_b32_e32 v2, v28
; CHECK-NEXT:    v_mov_b32_e32 v0, v27
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x86000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x85e00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 50
; CHECK-NEXT:    v_writelane_b32 v58, s7, 51
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_57
; CHECK-NEXT:    s_branch .LBB0_59
; CHECK-NEXT:  .LBB0_29:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x88200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x8e800
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x86000
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 52
; CHECK-NEXT:    v_writelane_b32 v58, s5, 53
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v24, v33
; CHECK-NEXT:    v_mov_b32_e32 v25, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8c800
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x86200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8a800
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(4)
; CHECK-NEXT:    v_mov_b32_e32 v2, v30
; CHECK-NEXT:    v_mov_b32_e32 v0, v29
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8a600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8a400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 54
; CHECK-NEXT:    v_writelane_b32 v58, s7, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_49
; CHECK-NEXT:    s_branch .LBB0_51
; CHECK-NEXT:  .LBB0_30:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x8c800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x92e00
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x8a600
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 56
; CHECK-NEXT:    v_writelane_b32 v58, s5, 57
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v26, v33
; CHECK-NEXT:    v_mov_b32_e32 v27, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x90e00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8a800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8ee00
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    v_mov_b32_e32 v2, v32
; CHECK-NEXT:    v_mov_b32_e32 v0, v31
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8ec00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8ea00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 58
; CHECK-NEXT:    v_writelane_b32 v58, s7, 59
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_41
; CHECK-NEXT:    s_branch .LBB0_43
; CHECK-NEXT:  .LBB0_31:
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x90e00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97400
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x8ec00
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    v_writelane_b32 v58, s4, 60
; CHECK-NEXT:    v_writelane_b32 v58, s5, 61
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[6:7], v[35:36], s[4:5]
; CHECK-NEXT:    s_mov_b32 s10, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s10
; CHECK-NEXT:    s_mov_b32 s10, s9
; CHECK-NEXT:    v_mov_b32_e32 v32, v34
; CHECK-NEXT:    v_mov_b32_e32 v35, s10
; CHECK-NEXT:    v_cndmask_b32_e64 v32, v32, v35, s[6:7]
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v34, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v33, v33, v34, s[6:7]
; CHECK-NEXT:    v_mov_b32_e32 v28, v33
; CHECK-NEXT:    v_mov_b32_e32 v29, v32
; CHECK-NEXT:    s_add_i32 s6, s32, 0x95400
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8ee00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x93400
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s6 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s6 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s6 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s6 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s6 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s6 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s6 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s6 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s6 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s6 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s6 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s6 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(14)
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s6 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s6 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s6 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s6 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s6 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s6 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s6 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s6 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s6 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s6 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s6 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s6 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s6 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s6 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v2, v34
; CHECK-NEXT:    v_mov_b32_e32 v0, v33
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    s_add_i32 s6, s32, 0x93200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s6, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v4, s6, v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v0
; CHECK-NEXT:    ; kill: def $vgpr2 killed $vgpr2 def $vgpr2_vgpr3 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v3, v4
; CHECK-NEXT:    s_add_i32 s6, s32, 0x93000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_nlt_f64_e64 s[4:5], |v[0:1]|, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1
; CHECK-NEXT:    s_mov_b64 s[6:7], exec
; CHECK-NEXT:    s_and_b64 s[4:5], s[6:7], s[4:5]
; CHECK-NEXT:    s_xor_b64 s[6:7], s[4:5], s[6:7]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 62
; CHECK-NEXT:    v_writelane_b32 v58, s7, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_33
; CHECK-NEXT:    s_branch .LBB0_35
; CHECK-NEXT:  .LBB0_32:
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:876 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x93400
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97700
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x93200
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v37, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_cmp_nlg_f64_e64 s[4:5], v[36:37], s[4:5]
; CHECK-NEXT:    s_mov_b32 s8, 0x7ff80000
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 def $sgpr6_sgpr7
; CHECK-NEXT:    s_mov_b32 s7, s8
; CHECK-NEXT:    s_mov_b32 s8, s6
; CHECK-NEXT:    v_mov_b32_e32 v0, v34
; CHECK-NEXT:    v_mov_b32_e32 v36, s8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v36, s[4:5]
; CHECK-NEXT:    s_mov_b32 s6, s7
; CHECK-NEXT:    v_mov_b32_e32 v34, v35
; CHECK-NEXT:    v_mov_b32_e32 v35, s6
; CHECK-NEXT:    v_cndmask_b32_e64 v34, v34, v35, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97600
; CHECK-NEXT:    buffer_store_dword v34, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s4, 0x7c
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v32
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x78
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v31
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x74
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v30
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x70
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v29
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x6c
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v28
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x68
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v27
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x64
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v26
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x60
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v25
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x5c
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v24
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x58
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v23
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x54
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v22
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x50
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v21
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x4c
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v20
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x48
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v19
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x44
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v18
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 64
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v17
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 60
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v16
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 56
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v15
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 52
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v14
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 48
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v13
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 44
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v12
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 40
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v11
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 36
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v10
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 32
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v9
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 28
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v8
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 24
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v7
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 20
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v6
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 16
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v5
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 12
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v4
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 8
; CHECK-NEXT:    v_add_i32_e32 v35, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v34, v3
; CHECK-NEXT:    buffer_store_dword v34, v35, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 4
; CHECK-NEXT:    v_add_i32_e32 v34, vcc, s4, v33
; CHECK-NEXT:    v_mov_b32_e32 v33, v2
; CHECK-NEXT:    buffer_store_dword v33, v34, s[0:3], 0 offen
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x95400
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 offset:8 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s4 offset:12 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s4 offset:16 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s4 offset:20 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s4 offset:24 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s4 offset:28 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s4 offset:32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s4 offset:36 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s4 offset:40 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s4 offset:44 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s4 offset:48 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s4 offset:52 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s4 offset:56 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s4 offset:60 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s4 offset:64 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s4 offset:68 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s4 offset:72 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s4 offset:76 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s4 offset:80 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s4 offset:84 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s4 offset:88 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s4 offset:92 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s4 offset:96 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s4 offset:100 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s4 offset:104 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s4 offset:108 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s4 offset:112 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s4 offset:116 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s4 offset:120 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s4 offset:124 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97600
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:876 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v4, v1
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xf4
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v34
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xf0
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v33
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xec
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v32
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xe8
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v31
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xe4
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v30
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xe0
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v29
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xdc
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v28
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xd8
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v27
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xd4
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v26
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xd0
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v25
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xcc
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v24
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xc8
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v23
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xc4
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v22
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xc0
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v21
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xbc
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v20
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xb8
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v19
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xb4
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v18
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xb0
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v17
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xac
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v16
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xa8
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v15
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xa4
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v14
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xa0
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v13
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x9c
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v12
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x98
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v11
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x94
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v10
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x90
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v9
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x8c
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v8
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x88
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v7
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x84
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v6
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0x80
; CHECK-NEXT:    v_add_i32_e32 v4, vcc, s4, v1
; CHECK-NEXT:    v_mov_b32_e32 v3, v5
; CHECK-NEXT:    buffer_store_dword v3, v4, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xfc
; CHECK-NEXT:    v_add_i32_e32 v3, vcc, s4, v1
; CHECK-NEXT:    buffer_store_dword v2, v3, s[0:3], 0 offen
; CHECK-NEXT:    s_mov_b32 s4, 0xf8
; CHECK-NEXT:    v_add_i32_e32 v1, vcc, s4, v1
; CHECK-NEXT:    buffer_store_dword v0, v1, s[0:3], 0 offen
; CHECK-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:136 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:140 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:144 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:148 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:152 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:156 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:160 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:164 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:168 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:172 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:176 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:180 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:184 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:188 ; 4-byte Folded Reload
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], -1
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbb900
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbba00
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
; CHECK-NEXT:  .LBB0_33: ; %Flow973
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 62
; CHECK-NEXT:    v_readlane_b32 s5, v59, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x97b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x97900
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 0
; CHECK-NEXT:    v_writelane_b32 v58, s5, 1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_39
; CHECK-NEXT:  ; %bb.34: ; %frem.compute
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 60
; CHECK-NEXT:    v_readlane_b32 s5, v59, 61
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x93000
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x98700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x98500
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0x98300
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 2
; CHECK-NEXT:    v_writelane_b32 v58, s5, 3
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97e00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 4
; CHECK-NEXT:    v_writelane_b32 v58, s5, 5
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_40
; CHECK-NEXT:    s_branch .LBB0_36
; CHECK-NEXT:  .LBB0_35: ; %frem.else
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_33
; CHECK-NEXT:  .LBB0_36: ; %frem.loop_body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 2
; CHECK-NEXT:    v_readlane_b32 s7, v58, 3
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98200
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98500
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 2
; CHECK-NEXT:    v_writelane_b32 v58, s7, 3
; CHECK-NEXT:    s_add_i32 s6, s32, 0x98200
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x98000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x98a00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x98800
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 6
; CHECK-NEXT:    v_writelane_b32 v58, s7, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_36
; CHECK-NEXT:  ; %bb.37: ; %Flow
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 6
; CHECK-NEXT:    v_readlane_b32 s5, v58, 7
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.38: ; %Flow
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98800
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97e00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_40
; CHECK-NEXT:  .LBB0_39: ; %Flow974
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 0
; CHECK-NEXT:    v_readlane_b32 s5, v58, 1
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97700
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_32
; CHECK-NEXT:  .LBB0_40: ; %frem.loop_exit
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 4
; CHECK-NEXT:    v_readlane_b32 s5, v58, 5
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98700
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97e00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97d00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_39
; CHECK-NEXT:  .LBB0_41: ; %Flow976
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 58
; CHECK-NEXT:    v_readlane_b32 s5, v59, 59
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x98d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x98b00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 8
; CHECK-NEXT:    v_writelane_b32 v58, s5, 9
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_47
; CHECK-NEXT:  ; %bb.42: ; %frem.compute15
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 56
; CHECK-NEXT:    v_readlane_b32 s5, v59, 57
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8ea00
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x99900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x99700
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0x99500
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 10
; CHECK-NEXT:    v_writelane_b32 v58, s5, 11
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99000
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 12
; CHECK-NEXT:    v_writelane_b32 v58, s5, 13
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_48
; CHECK-NEXT:    s_branch .LBB0_44
; CHECK-NEXT:  .LBB0_43: ; %frem.else16
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_41
; CHECK-NEXT:  .LBB0_44: ; %frem.loop_body23
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 10
; CHECK-NEXT:    v_readlane_b32 s7, v58, 11
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99400
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99700
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 10
; CHECK-NEXT:    v_writelane_b32 v58, s7, 11
; CHECK-NEXT:    s_add_i32 s6, s32, 0x99400
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x99200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x99c00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x99a00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 14
; CHECK-NEXT:    v_writelane_b32 v58, s7, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_44
; CHECK-NEXT:  ; %bb.45: ; %Flow975
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 14
; CHECK-NEXT:    v_readlane_b32 s5, v58, 15
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.46: ; %Flow975
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99a00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99000
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_48
; CHECK-NEXT:  .LBB0_47: ; %Flow977
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 8
; CHECK-NEXT:    v_readlane_b32 s5, v58, 9
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x97400
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_31
; CHECK-NEXT:  .LBB0_48: ; %frem.loop_exit24
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 12
; CHECK-NEXT:    v_readlane_b32 s5, v58, 13
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99900
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99000
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98f00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x98b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_47
; CHECK-NEXT:  .LBB0_49: ; %Flow979
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 54
; CHECK-NEXT:    v_readlane_b32 s5, v59, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x99f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x99d00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 16
; CHECK-NEXT:    v_writelane_b32 v58, s5, 17
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_55
; CHECK-NEXT:  ; %bb.50: ; %frem.compute46
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 52
; CHECK-NEXT:    v_readlane_b32 s5, v59, 53
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x8a400
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9ab00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9a900
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9a700
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 18
; CHECK-NEXT:    v_writelane_b32 v58, s5, 19
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a200
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 20
; CHECK-NEXT:    v_writelane_b32 v58, s5, 21
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_56
; CHECK-NEXT:    s_branch .LBB0_52
; CHECK-NEXT:  .LBB0_51: ; %frem.else47
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_49
; CHECK-NEXT:  .LBB0_52: ; %frem.loop_body54
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 18
; CHECK-NEXT:    v_readlane_b32 s7, v58, 19
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a600
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a900
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 18
; CHECK-NEXT:    v_writelane_b32 v58, s7, 19
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9a600
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9a400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9ae00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9ac00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 22
; CHECK-NEXT:    v_writelane_b32 v58, s7, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_52
; CHECK-NEXT:  ; %bb.53: ; %Flow978
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 22
; CHECK-NEXT:    v_readlane_b32 s5, v58, 23
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.54: ; %Flow978
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ae00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ac00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_56
; CHECK-NEXT:  .LBB0_55: ; %Flow980
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 16
; CHECK-NEXT:    v_readlane_b32 s5, v58, 17
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x92e00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_30
; CHECK-NEXT:  .LBB0_56: ; %frem.loop_exit55
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 20
; CHECK-NEXT:    v_readlane_b32 s5, v58, 21
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ab00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a200
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9a100
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x99d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_55
; CHECK-NEXT:  .LBB0_57: ; %Flow982
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 50
; CHECK-NEXT:    v_readlane_b32 s5, v59, 51
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9b100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9af00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 24
; CHECK-NEXT:    v_writelane_b32 v58, s5, 25
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_63
; CHECK-NEXT:  ; %bb.58: ; %frem.compute77
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 48
; CHECK-NEXT:    v_readlane_b32 s5, v59, 49
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x85e00
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9bd00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9bb00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9b900
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 26
; CHECK-NEXT:    v_writelane_b32 v58, s5, 27
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b400
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 28
; CHECK-NEXT:    v_writelane_b32 v58, s5, 29
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_64
; CHECK-NEXT:    s_branch .LBB0_60
; CHECK-NEXT:  .LBB0_59: ; %frem.else78
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_57
; CHECK-NEXT:  .LBB0_60: ; %frem.loop_body85
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 26
; CHECK-NEXT:    v_readlane_b32 s7, v58, 27
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b800
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9bb00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 26
; CHECK-NEXT:    v_writelane_b32 v58, s7, 27
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9b800
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9b600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9c000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9be00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 30
; CHECK-NEXT:    v_writelane_b32 v58, s7, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_60
; CHECK-NEXT:  ; %bb.61: ; %Flow981
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 30
; CHECK-NEXT:    v_readlane_b32 s5, v58, 31
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.62: ; %Flow981
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9be00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b400
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_64
; CHECK-NEXT:  .LBB0_63: ; %Flow983
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 24
; CHECK-NEXT:    v_readlane_b32 s5, v58, 25
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9af00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x8e800
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_29
; CHECK-NEXT:  .LBB0_64: ; %frem.loop_exit86
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 28
; CHECK-NEXT:    v_readlane_b32 s5, v58, 29
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9bd00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9bb00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b400
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9b300
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9af00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_63
; CHECK-NEXT:  .LBB0_65: ; %Flow985
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 46
; CHECK-NEXT:    v_readlane_b32 s5, v59, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9c300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9c100
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 32
; CHECK-NEXT:    v_writelane_b32 v58, s5, 33
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_71
; CHECK-NEXT:  ; %bb.66: ; %frem.compute108
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 44
; CHECK-NEXT:    v_readlane_b32 s5, v59, 45
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x81800
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9cf00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9cd00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9cb00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 34
; CHECK-NEXT:    v_writelane_b32 v58, s5, 35
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ca00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c600
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 36
; CHECK-NEXT:    v_writelane_b32 v58, s5, 37
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_72
; CHECK-NEXT:    s_branch .LBB0_68
; CHECK-NEXT:  .LBB0_67: ; %frem.else109
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_65
; CHECK-NEXT:  .LBB0_68: ; %frem.loop_body116
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 34
; CHECK-NEXT:    v_readlane_b32 s7, v58, 35
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ca00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9cd00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9cb00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 34
; CHECK-NEXT:    v_writelane_b32 v58, s7, 35
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9ca00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9c800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9d200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9d000
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 38
; CHECK-NEXT:    v_writelane_b32 v58, s7, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_68
; CHECK-NEXT:  ; %bb.69: ; %Flow984
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 38
; CHECK-NEXT:    v_readlane_b32 s5, v58, 39
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.70: ; %Flow984
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d000
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c600
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_72
; CHECK-NEXT:  .LBB0_71: ; %Flow986
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 32
; CHECK-NEXT:    v_readlane_b32 s5, v58, 33
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x8a200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_28
; CHECK-NEXT:  .LBB0_72: ; %frem.loop_exit117
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 36
; CHECK-NEXT:    v_readlane_b32 s5, v58, 37
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9cf00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9cd00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9cb00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c600
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c500
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9c100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_71
; CHECK-NEXT:  .LBB0_73: ; %Flow988
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 42
; CHECK-NEXT:    v_readlane_b32 s5, v59, 43
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9d500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9d300
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 40
; CHECK-NEXT:    v_writelane_b32 v58, s5, 41
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_79
; CHECK-NEXT:  ; %bb.74: ; %frem.compute139
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 40
; CHECK-NEXT:    v_readlane_b32 s5, v59, 41
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x7d200
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9e100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9df00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9dd00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 42
; CHECK-NEXT:    v_writelane_b32 v58, s5, 43
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9dc00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9da00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d800
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 44
; CHECK-NEXT:    v_writelane_b32 v58, s5, 45
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_80
; CHECK-NEXT:    s_branch .LBB0_76
; CHECK-NEXT:  .LBB0_75: ; %frem.else140
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_73
; CHECK-NEXT:  .LBB0_76: ; %frem.loop_body147
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 42
; CHECK-NEXT:    v_readlane_b32 s7, v58, 43
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9da00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9dc00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9df00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9dd00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 42
; CHECK-NEXT:    v_writelane_b32 v58, s7, 43
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9dc00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9da00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9e400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9e200
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 46
; CHECK-NEXT:    v_writelane_b32 v58, s7, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_76
; CHECK-NEXT:  ; %bb.77: ; %Flow987
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 46
; CHECK-NEXT:    v_readlane_b32 s5, v58, 47
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.78: ; %Flow987
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e200
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d800
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_80
; CHECK-NEXT:  .LBB0_79: ; %Flow989
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 40
; CHECK-NEXT:    v_readlane_b32 s5, v58, 41
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x85c00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_27
; CHECK-NEXT:  .LBB0_80: ; %frem.loop_exit148
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 44
; CHECK-NEXT:    v_readlane_b32 s5, v58, 45
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e100
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9df00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9dd00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d800
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d700
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9d300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_79
; CHECK-NEXT:  .LBB0_81: ; %Flow991
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 38
; CHECK-NEXT:    v_readlane_b32 s5, v59, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9e700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9e500
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 48
; CHECK-NEXT:    v_writelane_b32 v58, s5, 49
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_87
; CHECK-NEXT:  ; %bb.82: ; %frem.compute170
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 36
; CHECK-NEXT:    v_readlane_b32 s5, v59, 37
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x78c00
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9f300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9f100
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0x9ef00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 50
; CHECK-NEXT:    v_writelane_b32 v58, s5, 51
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ee00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ec00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ea00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 52
; CHECK-NEXT:    v_writelane_b32 v58, s5, 53
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_88
; CHECK-NEXT:    s_branch .LBB0_84
; CHECK-NEXT:  .LBB0_83: ; %frem.else171
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_81
; CHECK-NEXT:  .LBB0_84: ; %frem.loop_body178
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 50
; CHECK-NEXT:    v_readlane_b32 s7, v58, 51
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ec00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ee00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f100
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ef00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 50
; CHECK-NEXT:    v_writelane_b32 v58, s7, 51
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9ee00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9ec00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9f600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9f400
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 54
; CHECK-NEXT:    v_writelane_b32 v58, s7, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_84
; CHECK-NEXT:  ; %bb.85: ; %Flow990
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 54
; CHECK-NEXT:    v_readlane_b32 s5, v58, 55
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.86: ; %Flow990
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f400
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ea00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_88
; CHECK-NEXT:  .LBB0_87: ; %Flow992
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 48
; CHECK-NEXT:    v_readlane_b32 s5, v58, 49
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x81600
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_26
; CHECK-NEXT:  .LBB0_88: ; %frem.loop_exit179
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 52
; CHECK-NEXT:    v_readlane_b32 s5, v58, 53
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f300
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ef00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9ea00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e900
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9e500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_87
; CHECK-NEXT:  .LBB0_89: ; %Flow994
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 34
; CHECK-NEXT:    v_readlane_b32 s5, v58, 35
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9f900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9f700
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr58 : SGPR spill to VGPR lane
; CHECK-NEXT:    v_writelane_b32 v58, s4, 56
; CHECK-NEXT:    v_writelane_b32 v58, s5, 57
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_95
; CHECK-NEXT:  ; %bb.90: ; %frem.compute201
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 32
; CHECK-NEXT:    v_readlane_b32 s5, v59, 33
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x74600
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa0500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa0300
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa0100
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 58
; CHECK-NEXT:    v_writelane_b32 v58, s5, 59
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fe00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fc00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fb00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 60
; CHECK-NEXT:    v_writelane_b32 v58, s5, 61
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_96
; CHECK-NEXT:    s_branch .LBB0_92
; CHECK-NEXT:  .LBB0_91: ; %frem.else202
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_89
; CHECK-NEXT:  .LBB0_92: ; %frem.loop_body209
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 58
; CHECK-NEXT:    v_readlane_b32 s7, v58, 59
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fe00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0000
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0300
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 58
; CHECK-NEXT:    v_writelane_b32 v58, s7, 59
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa0000
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0x9fe00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa0800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa0600
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 62
; CHECK-NEXT:    v_writelane_b32 v58, s7, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_92
; CHECK-NEXT:  ; %bb.93: ; %Flow993
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 62
; CHECK-NEXT:    v_readlane_b32 s5, v58, 63
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.94: ; %Flow993
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0600
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fc00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fb00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_96
; CHECK-NEXT:  .LBB0_95: ; %Flow995
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 56
; CHECK-NEXT:    v_readlane_b32 s5, v58, 57
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x7d000
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_25
; CHECK-NEXT:  .LBB0_96: ; %frem.loop_exit210
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 60
; CHECK-NEXT:    v_readlane_b32 s5, v58, 61
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0500
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fc00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9fb00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0x9f700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_95
; CHECK-NEXT:  .LBB0_97: ; %Flow997
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 30
; CHECK-NEXT:    v_readlane_b32 s5, v59, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa0b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa0900
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 0
; CHECK-NEXT:    v_writelane_b32 v58, s5, 1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_103
; CHECK-NEXT:  ; %bb.98: ; %frem.compute232
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 28
; CHECK-NEXT:    v_readlane_b32 s5, v59, 29
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x70000
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa1700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa1500
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa1300
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 2
; CHECK-NEXT:    v_writelane_b32 v58, s5, 3
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0e00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 4
; CHECK-NEXT:    v_writelane_b32 v58, s5, 5
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_104
; CHECK-NEXT:    s_branch .LBB0_100
; CHECK-NEXT:  .LBB0_99: ; %frem.else233
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_97
; CHECK-NEXT:  .LBB0_100: ; %frem.loop_body240
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 2
; CHECK-NEXT:    v_readlane_b32 s7, v58, 3
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1200
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1500
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 2
; CHECK-NEXT:    v_writelane_b32 v58, s7, 3
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa1200
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa1000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa1a00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa1800
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 6
; CHECK-NEXT:    v_writelane_b32 v58, s7, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_100
; CHECK-NEXT:  ; %bb.101: ; %Flow996
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 6
; CHECK-NEXT:    v_readlane_b32 s5, v58, 7
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.102: ; %Flow996
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1800
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0e00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_104
; CHECK-NEXT:  .LBB0_103: ; %Flow998
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 0
; CHECK-NEXT:    v_readlane_b32 s5, v58, 1
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x78a00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_24
; CHECK-NEXT:  .LBB0_104: ; %frem.loop_exit241
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 4
; CHECK-NEXT:    v_readlane_b32 s5, v58, 5
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1700
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0e00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0d00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa0900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_103
; CHECK-NEXT:  .LBB0_105: ; %Flow1000
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 26
; CHECK-NEXT:    v_readlane_b32 s5, v59, 27
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa1d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa1b00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 8
; CHECK-NEXT:    v_writelane_b32 v58, s5, 9
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_111
; CHECK-NEXT:  ; %bb.106: ; %frem.compute263
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 24
; CHECK-NEXT:    v_readlane_b32 s5, v59, 25
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x6ba00
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa2900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa2700
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa2500
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 10
; CHECK-NEXT:    v_writelane_b32 v58, s5, 11
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2000
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 12
; CHECK-NEXT:    v_writelane_b32 v58, s5, 13
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_112
; CHECK-NEXT:    s_branch .LBB0_108
; CHECK-NEXT:  .LBB0_107: ; %frem.else264
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_105
; CHECK-NEXT:  .LBB0_108: ; %frem.loop_body271
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 10
; CHECK-NEXT:    v_readlane_b32 s7, v58, 11
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2400
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2700
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 10
; CHECK-NEXT:    v_writelane_b32 v58, s7, 11
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa2400
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa2200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa2c00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa2a00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 14
; CHECK-NEXT:    v_writelane_b32 v58, s7, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_108
; CHECK-NEXT:  ; %bb.109: ; %Flow999
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 14
; CHECK-NEXT:    v_readlane_b32 s5, v58, 15
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.110: ; %Flow999
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2a00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2000
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_112
; CHECK-NEXT:  .LBB0_111: ; %Flow1001
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 8
; CHECK-NEXT:    v_readlane_b32 s5, v58, 9
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x74400
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_23
; CHECK-NEXT:  .LBB0_112: ; %frem.loop_exit272
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 12
; CHECK-NEXT:    v_readlane_b32 s5, v58, 13
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2900
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2000
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1f00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa1b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_111
; CHECK-NEXT:  .LBB0_113: ; %Flow1003
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 22
; CHECK-NEXT:    v_readlane_b32 s5, v59, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa2f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa2d00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 16
; CHECK-NEXT:    v_writelane_b32 v58, s5, 17
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_119
; CHECK-NEXT:  ; %bb.114: ; %frem.compute294
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 20
; CHECK-NEXT:    v_readlane_b32 s5, v59, 21
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x67400
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa3b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa3900
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa3700
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 18
; CHECK-NEXT:    v_writelane_b32 v58, s5, 19
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3200
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 20
; CHECK-NEXT:    v_writelane_b32 v58, s5, 21
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_120
; CHECK-NEXT:    s_branch .LBB0_116
; CHECK-NEXT:  .LBB0_115: ; %frem.else295
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_113
; CHECK-NEXT:  .LBB0_116: ; %frem.loop_body302
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 18
; CHECK-NEXT:    v_readlane_b32 s7, v58, 19
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3600
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3900
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 18
; CHECK-NEXT:    v_writelane_b32 v58, s7, 19
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa3600
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa3400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa3e00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa3c00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 22
; CHECK-NEXT:    v_writelane_b32 v58, s7, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_116
; CHECK-NEXT:  ; %bb.117: ; %Flow1002
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 22
; CHECK-NEXT:    v_readlane_b32 s5, v58, 23
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.118: ; %Flow1002
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3e00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3c00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_120
; CHECK-NEXT:  .LBB0_119: ; %Flow1004
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 16
; CHECK-NEXT:    v_readlane_b32 s5, v58, 17
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x6fe00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_22
; CHECK-NEXT:  .LBB0_120: ; %frem.loop_exit303
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 20
; CHECK-NEXT:    v_readlane_b32 s5, v58, 21
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3b00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3200
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3100
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa2d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_119
; CHECK-NEXT:  .LBB0_121: ; %Flow1006
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 18
; CHECK-NEXT:    v_readlane_b32 s5, v59, 19
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa4100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa3f00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 24
; CHECK-NEXT:    v_writelane_b32 v58, s5, 25
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_127
; CHECK-NEXT:  ; %bb.122: ; %frem.compute325
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 16
; CHECK-NEXT:    v_readlane_b32 s5, v59, 17
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x62e00
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa4d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa4b00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa4900
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 26
; CHECK-NEXT:    v_writelane_b32 v58, s5, 27
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4400
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 28
; CHECK-NEXT:    v_writelane_b32 v58, s5, 29
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_128
; CHECK-NEXT:    s_branch .LBB0_124
; CHECK-NEXT:  .LBB0_123: ; %frem.else326
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_121
; CHECK-NEXT:  .LBB0_124: ; %frem.loop_body333
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 26
; CHECK-NEXT:    v_readlane_b32 s7, v58, 27
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4800
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4b00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 26
; CHECK-NEXT:    v_writelane_b32 v58, s7, 27
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa4800
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa4600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa5000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa4e00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 30
; CHECK-NEXT:    v_writelane_b32 v58, s7, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_124
; CHECK-NEXT:  ; %bb.125: ; %Flow1005
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 30
; CHECK-NEXT:    v_readlane_b32 s5, v58, 31
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.126: ; %Flow1005
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4e00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4400
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_128
; CHECK-NEXT:  .LBB0_127: ; %Flow1007
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 24
; CHECK-NEXT:    v_readlane_b32 s5, v58, 25
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x6b800
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_21
; CHECK-NEXT:  .LBB0_128: ; %frem.loop_exit334
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 28
; CHECK-NEXT:    v_readlane_b32 s5, v58, 29
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4d00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4b00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4400
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa4300
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa3f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_127
; CHECK-NEXT:  .LBB0_129: ; %Flow1009
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 14
; CHECK-NEXT:    v_readlane_b32 s5, v59, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa5300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa5100
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 32
; CHECK-NEXT:    v_writelane_b32 v58, s5, 33
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_135
; CHECK-NEXT:  ; %bb.130: ; %frem.compute356
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 12
; CHECK-NEXT:    v_readlane_b32 s5, v59, 13
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5e800
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa5f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa5d00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa5b00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 34
; CHECK-NEXT:    v_writelane_b32 v58, s5, 35
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5a00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5600
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 36
; CHECK-NEXT:    v_writelane_b32 v58, s5, 37
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_136
; CHECK-NEXT:    s_branch .LBB0_132
; CHECK-NEXT:  .LBB0_131: ; %frem.else357
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_129
; CHECK-NEXT:  .LBB0_132: ; %frem.loop_body364
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 34
; CHECK-NEXT:    v_readlane_b32 s7, v58, 35
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5a00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5d00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5b00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 34
; CHECK-NEXT:    v_writelane_b32 v58, s7, 35
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa5a00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa5800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa6200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa6000
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 38
; CHECK-NEXT:    v_writelane_b32 v58, s7, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_132
; CHECK-NEXT:  ; %bb.133: ; %Flow1008
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 38
; CHECK-NEXT:    v_readlane_b32 s5, v58, 39
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.134: ; %Flow1008
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6000
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5600
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_136
; CHECK-NEXT:  .LBB0_135: ; %Flow1010
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 32
; CHECK-NEXT:    v_readlane_b32 s5, v58, 33
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x67200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_20
; CHECK-NEXT:  .LBB0_136: ; %frem.loop_exit365
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 36
; CHECK-NEXT:    v_readlane_b32 s5, v58, 37
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5f00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5d00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5600
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5500
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa5100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_135
; CHECK-NEXT:  .LBB0_137: ; %Flow1012
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 10
; CHECK-NEXT:    v_readlane_b32 s5, v59, 11
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa6500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa6300
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 40
; CHECK-NEXT:    v_writelane_b32 v58, s5, 41
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_143
; CHECK-NEXT:  ; %bb.138: ; %frem.compute387
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 8
; CHECK-NEXT:    v_readlane_b32 s5, v59, 9
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x5a200
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa7100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa6f00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa6d00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 42
; CHECK-NEXT:    v_writelane_b32 v58, s5, 43
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6a00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6800
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 44
; CHECK-NEXT:    v_writelane_b32 v58, s5, 45
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_144
; CHECK-NEXT:    s_branch .LBB0_140
; CHECK-NEXT:  .LBB0_139: ; %frem.else388
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_137
; CHECK-NEXT:  .LBB0_140: ; %frem.loop_body395
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 42
; CHECK-NEXT:    v_readlane_b32 s7, v58, 43
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6c00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6f00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6d00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 42
; CHECK-NEXT:    v_writelane_b32 v58, s7, 43
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa6c00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa6a00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa7400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa7200
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 46
; CHECK-NEXT:    v_writelane_b32 v58, s7, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_140
; CHECK-NEXT:  ; %bb.141: ; %Flow1011
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 46
; CHECK-NEXT:    v_readlane_b32 s5, v58, 47
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.142: ; %Flow1011
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7200
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6800
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_144
; CHECK-NEXT:  .LBB0_143: ; %Flow1013
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 40
; CHECK-NEXT:    v_readlane_b32 s5, v58, 41
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x62c00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_19
; CHECK-NEXT:  .LBB0_144: ; %frem.loop_exit396
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 44
; CHECK-NEXT:    v_readlane_b32 s5, v58, 45
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7100
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6f00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6800
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6700
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa6300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_143
; CHECK-NEXT:  .LBB0_145: ; %Flow1015
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 6
; CHECK-NEXT:    v_readlane_b32 s5, v59, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa7700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa7500
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 48
; CHECK-NEXT:    v_writelane_b32 v58, s5, 49
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_151
; CHECK-NEXT:  ; %bb.146: ; %frem.compute418
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 4
; CHECK-NEXT:    v_readlane_b32 s5, v59, 5
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x55c00
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa8300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa8100
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa7f00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 50
; CHECK-NEXT:    v_writelane_b32 v58, s5, 51
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7e00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7a00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 52
; CHECK-NEXT:    v_writelane_b32 v58, s5, 53
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_152
; CHECK-NEXT:    s_branch .LBB0_148
; CHECK-NEXT:  .LBB0_147: ; %frem.else419
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_145
; CHECK-NEXT:  .LBB0_148: ; %frem.loop_body426
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 50
; CHECK-NEXT:    v_readlane_b32 s7, v58, 51
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7e00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8100
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7f00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 50
; CHECK-NEXT:    v_writelane_b32 v58, s7, 51
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa7e00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa7c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa8600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa8400
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 54
; CHECK-NEXT:    v_writelane_b32 v58, s7, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_148
; CHECK-NEXT:  ; %bb.149: ; %Flow1014
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 54
; CHECK-NEXT:    v_readlane_b32 s5, v58, 55
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.150: ; %Flow1014
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8400
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7a00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_152
; CHECK-NEXT:  .LBB0_151: ; %Flow1016
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 48
; CHECK-NEXT:    v_readlane_b32 s5, v58, 49
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x5e600
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_18
; CHECK-NEXT:  .LBB0_152: ; %frem.loop_exit427
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 52
; CHECK-NEXT:    v_readlane_b32 s5, v58, 53
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8300
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7a00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7900
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa7500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_151
; CHECK-NEXT:  .LBB0_153: ; %Flow1018
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 2
; CHECK-NEXT:    v_readlane_b32 s5, v58, 3
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa8900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa8700
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr58 : SGPR spill to VGPR lane
; CHECK-NEXT:    v_writelane_b32 v58, s4, 56
; CHECK-NEXT:    v_writelane_b32 v58, s5, 57
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_159
; CHECK-NEXT:  ; %bb.154: ; %frem.compute449
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 0
; CHECK-NEXT:    v_readlane_b32 s5, v59, 1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x51600
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa9500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa9300
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xa9100
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 58
; CHECK-NEXT:    v_writelane_b32 v58, s5, 59
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8e00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8c00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 60
; CHECK-NEXT:    v_writelane_b32 v58, s5, 61
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_160
; CHECK-NEXT:    s_branch .LBB0_156
; CHECK-NEXT:  .LBB0_155: ; %frem.else450
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_153
; CHECK-NEXT:  .LBB0_156: ; %frem.loop_body457
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 58
; CHECK-NEXT:    v_readlane_b32 s7, v58, 59
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8e00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9000
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9300
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 58
; CHECK-NEXT:    v_writelane_b32 v58, s7, 59
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa9000
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa8e00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa9800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa9600
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 62
; CHECK-NEXT:    v_writelane_b32 v58, s7, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_156
; CHECK-NEXT:  ; %bb.157: ; %Flow1017
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 62
; CHECK-NEXT:    v_readlane_b32 s5, v58, 63
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.158: ; %Flow1017
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9600
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8c00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_160
; CHECK-NEXT:  .LBB0_159: ; %Flow1019
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 56
; CHECK-NEXT:    v_readlane_b32 s5, v58, 57
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x5a000
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_17
; CHECK-NEXT:  .LBB0_160: ; %frem.loop_exit458
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 60
; CHECK-NEXT:    v_readlane_b32 s5, v58, 61
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9500
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8c00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8b00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa8700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_159
; CHECK-NEXT:  .LBB0_161: ; %Flow1021
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 62
; CHECK-NEXT:    v_readlane_b32 s5, v59, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa9b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xa9900
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 0
; CHECK-NEXT:    v_writelane_b32 v58, s5, 1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_167
; CHECK-NEXT:  ; %bb.162: ; %frem.compute480
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 60
; CHECK-NEXT:    v_readlane_b32 s5, v59, 61
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x4d000
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xaa700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xaa500
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xaa300
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 2
; CHECK-NEXT:    v_writelane_b32 v58, s5, 3
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9e00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 4
; CHECK-NEXT:    v_writelane_b32 v58, s5, 5
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_168
; CHECK-NEXT:    s_branch .LBB0_164
; CHECK-NEXT:  .LBB0_163: ; %frem.else481
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_161
; CHECK-NEXT:  .LBB0_164: ; %frem.loop_body488
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 2
; CHECK-NEXT:    v_readlane_b32 s7, v58, 3
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa200
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa500
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 2
; CHECK-NEXT:    v_writelane_b32 v58, s7, 3
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaa200
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaa000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaaa00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaa800
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 6
; CHECK-NEXT:    v_writelane_b32 v58, s7, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_164
; CHECK-NEXT:  ; %bb.165: ; %Flow1020
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 6
; CHECK-NEXT:    v_readlane_b32 s5, v58, 7
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.166: ; %Flow1020
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaaa00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa800
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9e00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_168
; CHECK-NEXT:  .LBB0_167: ; %Flow1022
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 0
; CHECK-NEXT:    v_readlane_b32 s5, v58, 1
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x55a00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_16
; CHECK-NEXT:  .LBB0_168: ; %frem.loop_exit489
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 4
; CHECK-NEXT:    v_readlane_b32 s5, v58, 5
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa700
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaa300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9e00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9d00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xa9900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_167
; CHECK-NEXT:  .LBB0_169: ; %Flow1024
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 58
; CHECK-NEXT:    v_readlane_b32 s5, v59, 59
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaad00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaab00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 8
; CHECK-NEXT:    v_writelane_b32 v58, s5, 9
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_175
; CHECK-NEXT:  ; %bb.170: ; %frem.compute511
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 56
; CHECK-NEXT:    v_readlane_b32 s5, v59, 57
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x48a00
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xab900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xab700
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xab500
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 10
; CHECK-NEXT:    v_writelane_b32 v58, s5, 11
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab000
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaaf00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 12
; CHECK-NEXT:    v_writelane_b32 v58, s5, 13
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_176
; CHECK-NEXT:    s_branch .LBB0_172
; CHECK-NEXT:  .LBB0_171: ; %frem.else512
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaad00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_169
; CHECK-NEXT:  .LBB0_172: ; %frem.loop_body519
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 10
; CHECK-NEXT:    v_readlane_b32 s7, v58, 11
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab400
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab700
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 10
; CHECK-NEXT:    v_writelane_b32 v58, s7, 11
; CHECK-NEXT:    s_add_i32 s6, s32, 0xab400
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xab200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xabc00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaba00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 14
; CHECK-NEXT:    v_writelane_b32 v58, s7, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_172
; CHECK-NEXT:  ; %bb.173: ; %Flow1023
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 14
; CHECK-NEXT:    v_readlane_b32 s5, v58, 15
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.174: ; %Flow1023
; CHECK-NEXT:    s_add_i32 s4, s32, 0xabc00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaba00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab000
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaaf00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_176
; CHECK-NEXT:  .LBB0_175: ; %Flow1025
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 8
; CHECK-NEXT:    v_readlane_b32 s5, v58, 9
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaab00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x51400
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_15
; CHECK-NEXT:  .LBB0_176: ; %frem.loop_exit520
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 12
; CHECK-NEXT:    v_readlane_b32 s5, v58, 13
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab900
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xab000
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaaf00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaab00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_175
; CHECK-NEXT:  .LBB0_177: ; %Flow1027
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 54
; CHECK-NEXT:    v_readlane_b32 s5, v59, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xabf00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xabd00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 16
; CHECK-NEXT:    v_writelane_b32 v58, s5, 17
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_183
; CHECK-NEXT:  ; %bb.178: ; %frem.compute542
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 52
; CHECK-NEXT:    v_readlane_b32 s5, v59, 53
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0x44400
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xacb00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xac900
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xac700
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 18
; CHECK-NEXT:    v_writelane_b32 v58, s5, 19
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac200
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 20
; CHECK-NEXT:    v_writelane_b32 v58, s5, 21
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_184
; CHECK-NEXT:    s_branch .LBB0_180
; CHECK-NEXT:  .LBB0_179: ; %frem.else543
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xabf00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_177
; CHECK-NEXT:  .LBB0_180: ; %frem.loop_body550
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 18
; CHECK-NEXT:    v_readlane_b32 s7, v58, 19
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac600
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac900
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 18
; CHECK-NEXT:    v_writelane_b32 v58, s7, 19
; CHECK-NEXT:    s_add_i32 s6, s32, 0xac600
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xac400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xace00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xacc00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 22
; CHECK-NEXT:    v_writelane_b32 v58, s7, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_180
; CHECK-NEXT:  ; %bb.181: ; %Flow1026
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 22
; CHECK-NEXT:    v_readlane_b32 s5, v58, 23
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.182: ; %Flow1026
; CHECK-NEXT:    s_add_i32 s4, s32, 0xace00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xacc00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_184
; CHECK-NEXT:  .LBB0_183: ; %Flow1028
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 16
; CHECK-NEXT:    v_readlane_b32 s5, v58, 17
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xabd00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x4ce00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_14
; CHECK-NEXT:  .LBB0_184: ; %frem.loop_exit551
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 20
; CHECK-NEXT:    v_readlane_b32 s5, v58, 21
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xacb00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac200
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xac100
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xabd00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_183
; CHECK-NEXT:  .LBB0_185: ; %Flow1030
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 50
; CHECK-NEXT:    v_readlane_b32 s5, v59, 51
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xad100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xacf00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 24
; CHECK-NEXT:    v_writelane_b32 v58, s5, 25
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_191
; CHECK-NEXT:  ; %bb.186: ; %frem.compute573
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 48
; CHECK-NEXT:    v_readlane_b32 s5, v59, 49
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:4088 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:4092 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xadd00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xadb00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xad900
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 26
; CHECK-NEXT:    v_writelane_b32 v58, s5, 27
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad400
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 28
; CHECK-NEXT:    v_writelane_b32 v58, s5, 29
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_192
; CHECK-NEXT:    s_branch .LBB0_188
; CHECK-NEXT:  .LBB0_187: ; %frem.else574
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_185
; CHECK-NEXT:  .LBB0_188: ; %frem.loop_body581
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 26
; CHECK-NEXT:    v_readlane_b32 s7, v58, 27
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad800
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xadb00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 26
; CHECK-NEXT:    v_writelane_b32 v58, s7, 27
; CHECK-NEXT:    s_add_i32 s6, s32, 0xad800
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xad600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xae000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xade00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 30
; CHECK-NEXT:    v_writelane_b32 v58, s7, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_188
; CHECK-NEXT:  ; %bb.189: ; %Flow1029
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 30
; CHECK-NEXT:    v_readlane_b32 s5, v58, 31
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.190: ; %Flow1029
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xade00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad400
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_192
; CHECK-NEXT:  .LBB0_191: ; %Flow1031
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 24
; CHECK-NEXT:    v_readlane_b32 s5, v58, 25
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xacf00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x48800
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_13
; CHECK-NEXT:  .LBB0_192: ; %frem.loop_exit582
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 28
; CHECK-NEXT:    v_readlane_b32 s5, v58, 29
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xadd00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xadb00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad400
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xad300
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xacf00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_191
; CHECK-NEXT:  .LBB0_193: ; %Flow1033
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 46
; CHECK-NEXT:    v_readlane_b32 s5, v59, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xae300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xae100
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 32
; CHECK-NEXT:    v_writelane_b32 v58, s5, 33
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_199
; CHECK-NEXT:  ; %bb.194: ; %frem.compute604
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 44
; CHECK-NEXT:    v_readlane_b32 s5, v59, 45
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3808 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3812 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xaef00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xaed00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xaeb00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 34
; CHECK-NEXT:    v_writelane_b32 v58, s5, 35
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaea00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae600
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 36
; CHECK-NEXT:    v_writelane_b32 v58, s5, 37
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_200
; CHECK-NEXT:    s_branch .LBB0_196
; CHECK-NEXT:  .LBB0_195: ; %frem.else605
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_193
; CHECK-NEXT:  .LBB0_196: ; %frem.loop_body612
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 34
; CHECK-NEXT:    v_readlane_b32 s7, v58, 35
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaea00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaed00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaeb00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 34
; CHECK-NEXT:    v_writelane_b32 v58, s7, 35
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaea00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xae800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaf200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaf000
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 38
; CHECK-NEXT:    v_writelane_b32 v58, s7, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_196
; CHECK-NEXT:  ; %bb.197: ; %Flow1032
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 38
; CHECK-NEXT:    v_readlane_b32 s5, v58, 39
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.198: ; %Flow1032
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf000
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae600
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_200
; CHECK-NEXT:  .LBB0_199: ; %Flow1034
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 32
; CHECK-NEXT:    v_readlane_b32 s5, v58, 33
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0x44200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_12
; CHECK-NEXT:  .LBB0_200: ; %frem.loop_exit613
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 36
; CHECK-NEXT:    v_readlane_b32 s5, v58, 37
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaef00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaed00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaeb00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae600
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae500
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xae100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_199
; CHECK-NEXT:  .LBB0_201: ; %Flow1036
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 42
; CHECK-NEXT:    v_readlane_b32 s5, v59, 43
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaf500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xaf300
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 40
; CHECK-NEXT:    v_writelane_b32 v58, s5, 41
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_207
; CHECK-NEXT:  ; %bb.202: ; %frem.compute635
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 40
; CHECK-NEXT:    v_readlane_b32 s5, v59, 41
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3528 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3532 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb0100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xaff00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xafd00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 42
; CHECK-NEXT:    v_writelane_b32 v58, s5, 43
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xafc00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xafa00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf800
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 44
; CHECK-NEXT:    v_writelane_b32 v58, s5, 45
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_208
; CHECK-NEXT:    s_branch .LBB0_204
; CHECK-NEXT:  .LBB0_203: ; %frem.else636
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_201
; CHECK-NEXT:  .LBB0_204: ; %frem.loop_body643
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 42
; CHECK-NEXT:    v_readlane_b32 s7, v58, 43
; CHECK-NEXT:    s_add_i32 s4, s32, 0xafa00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xafc00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaff00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xafd00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 42
; CHECK-NEXT:    v_writelane_b32 v58, s7, 43
; CHECK-NEXT:    s_add_i32 s6, s32, 0xafc00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xafa00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb0400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb0200
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 46
; CHECK-NEXT:    v_writelane_b32 v58, s7, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_204
; CHECK-NEXT:  ; %bb.205: ; %Flow1035
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 46
; CHECK-NEXT:    v_readlane_b32 s5, v58, 47
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.206: ; %Flow1035
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0200
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf800
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_208
; CHECK-NEXT:  .LBB0_207: ; %Flow1037
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 40
; CHECK-NEXT:    v_readlane_b32 s5, v58, 41
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:4080 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:4084 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_11
; CHECK-NEXT:  .LBB0_208: ; %frem.loop_exit644
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 44
; CHECK-NEXT:    v_readlane_b32 s5, v58, 45
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0100
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaff00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xafd00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf800
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf700
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xaf300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_207
; CHECK-NEXT:  .LBB0_209: ; %Flow1039
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 38
; CHECK-NEXT:    v_readlane_b32 s5, v59, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb0700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb0500
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 48
; CHECK-NEXT:    v_writelane_b32 v58, s5, 49
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_215
; CHECK-NEXT:  ; %bb.210: ; %frem.compute666
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 36
; CHECK-NEXT:    v_readlane_b32 s5, v59, 37
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:3248 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:3252 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb1300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb1100
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb0f00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 50
; CHECK-NEXT:    v_writelane_b32 v58, s5, 51
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0e00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0a00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 52
; CHECK-NEXT:    v_writelane_b32 v58, s5, 53
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_216
; CHECK-NEXT:    s_branch .LBB0_212
; CHECK-NEXT:  .LBB0_211: ; %frem.else667
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_209
; CHECK-NEXT:  .LBB0_212: ; %frem.loop_body674
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 50
; CHECK-NEXT:    v_readlane_b32 s7, v58, 51
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0e00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1100
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0f00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 50
; CHECK-NEXT:    v_writelane_b32 v58, s7, 51
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb0e00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb0c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb1600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb1400
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 54
; CHECK-NEXT:    v_writelane_b32 v58, s7, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_212
; CHECK-NEXT:  ; %bb.213: ; %Flow1038
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 54
; CHECK-NEXT:    v_readlane_b32 s5, v58, 55
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.214: ; %Flow1038
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1400
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0a00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_216
; CHECK-NEXT:  .LBB0_215: ; %Flow1040
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 48
; CHECK-NEXT:    v_readlane_b32 s5, v58, 49
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3800 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3804 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_10
; CHECK-NEXT:  .LBB0_216: ; %frem.loop_exit675
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 52
; CHECK-NEXT:    v_readlane_b32 s5, v58, 53
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1300
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0a00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0900
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb0500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_215
; CHECK-NEXT:  .LBB0_217: ; %Flow1042
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 34
; CHECK-NEXT:    v_readlane_b32 s5, v58, 35
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb1900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb1700
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr58 : SGPR spill to VGPR lane
; CHECK-NEXT:    v_writelane_b32 v58, s4, 56
; CHECK-NEXT:    v_writelane_b32 v58, s5, 57
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_223
; CHECK-NEXT:  ; %bb.218: ; %frem.compute697
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 32
; CHECK-NEXT:    v_readlane_b32 s5, v59, 33
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2968 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2972 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb2500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb2300
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb2100
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 58
; CHECK-NEXT:    v_writelane_b32 v58, s5, 59
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1e00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1c00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 60
; CHECK-NEXT:    v_writelane_b32 v58, s5, 61
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_224
; CHECK-NEXT:    s_branch .LBB0_220
; CHECK-NEXT:  .LBB0_219: ; %frem.else698
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_217
; CHECK-NEXT:  .LBB0_220: ; %frem.loop_body705
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 58
; CHECK-NEXT:    v_readlane_b32 s7, v58, 59
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1e00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2000
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2300
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 58
; CHECK-NEXT:    v_writelane_b32 v58, s7, 59
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb2000
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb1e00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb2800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb2600
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 62
; CHECK-NEXT:    v_writelane_b32 v58, s7, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_220
; CHECK-NEXT:  ; %bb.221: ; %Flow1041
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 62
; CHECK-NEXT:    v_readlane_b32 s5, v58, 63
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.222: ; %Flow1041
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2600
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1c00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_224
; CHECK-NEXT:  .LBB0_223: ; %Flow1043
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 56
; CHECK-NEXT:    v_readlane_b32 s5, v58, 57
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3520 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3524 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_9
; CHECK-NEXT:  .LBB0_224: ; %frem.loop_exit706
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 60
; CHECK-NEXT:    v_readlane_b32 s5, v58, 61
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2500
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1c00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1b00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb1700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_223
; CHECK-NEXT:  .LBB0_225: ; %Flow1045
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 30
; CHECK-NEXT:    v_readlane_b32 s5, v59, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb2b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb2900
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 0
; CHECK-NEXT:    v_writelane_b32 v58, s5, 1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_231
; CHECK-NEXT:  ; %bb.226: ; %frem.compute728
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 28
; CHECK-NEXT:    v_readlane_b32 s5, v59, 29
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2688 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2692 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb3700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb3500
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb3300
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 2
; CHECK-NEXT:    v_writelane_b32 v58, s5, 3
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2e00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 4
; CHECK-NEXT:    v_writelane_b32 v58, s5, 5
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_232
; CHECK-NEXT:    s_branch .LBB0_228
; CHECK-NEXT:  .LBB0_227: ; %frem.else729
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_225
; CHECK-NEXT:  .LBB0_228: ; %frem.loop_body736
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 2
; CHECK-NEXT:    v_readlane_b32 s7, v58, 3
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3200
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3500
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 2
; CHECK-NEXT:    v_writelane_b32 v58, s7, 3
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb3200
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb3000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb3a00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb3800
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 6
; CHECK-NEXT:    v_writelane_b32 v58, s7, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_228
; CHECK-NEXT:  ; %bb.229: ; %Flow1044
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 6
; CHECK-NEXT:    v_readlane_b32 s5, v58, 7
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.230: ; %Flow1044
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3800
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2e00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_232
; CHECK-NEXT:  .LBB0_231: ; %Flow1046
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 0
; CHECK-NEXT:    v_readlane_b32 s5, v58, 1
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:3240 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:3244 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_8
; CHECK-NEXT:  .LBB0_232: ; %frem.loop_exit737
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 4
; CHECK-NEXT:    v_readlane_b32 s5, v58, 5
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3700
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2e00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2d00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb2900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_231
; CHECK-NEXT:  .LBB0_233: ; %Flow1048
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 26
; CHECK-NEXT:    v_readlane_b32 s5, v59, 27
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb3d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb3b00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 8
; CHECK-NEXT:    v_writelane_b32 v58, s5, 9
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_239
; CHECK-NEXT:  ; %bb.234: ; %frem.compute759
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 24
; CHECK-NEXT:    v_readlane_b32 s5, v59, 25
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2408 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2412 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb4900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb4700
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb4500
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 10
; CHECK-NEXT:    v_writelane_b32 v58, s5, 11
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4000
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 12
; CHECK-NEXT:    v_writelane_b32 v58, s5, 13
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_240
; CHECK-NEXT:    s_branch .LBB0_236
; CHECK-NEXT:  .LBB0_235: ; %frem.else760
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_233
; CHECK-NEXT:  .LBB0_236: ; %frem.loop_body767
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 10
; CHECK-NEXT:    v_readlane_b32 s7, v58, 11
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4400
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4700
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4500
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 10
; CHECK-NEXT:    v_writelane_b32 v58, s7, 11
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb4400
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb4200
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb4c00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb4a00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 14
; CHECK-NEXT:    v_writelane_b32 v58, s7, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_236
; CHECK-NEXT:  ; %bb.237: ; %Flow1047
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 14
; CHECK-NEXT:    v_readlane_b32 s5, v58, 15
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.238: ; %Flow1047
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4a00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4000
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_240
; CHECK-NEXT:  .LBB0_239: ; %Flow1049
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 8
; CHECK-NEXT:    v_readlane_b32 s5, v58, 9
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2960 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2964 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_7
; CHECK-NEXT:  .LBB0_240: ; %frem.loop_exit768
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 12
; CHECK-NEXT:    v_readlane_b32 s5, v58, 13
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4900
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4000
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3f00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb3b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_239
; CHECK-NEXT:  .LBB0_241: ; %Flow1051
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 22
; CHECK-NEXT:    v_readlane_b32 s5, v59, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb4f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb4d00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 16
; CHECK-NEXT:    v_writelane_b32 v58, s5, 17
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_247
; CHECK-NEXT:  ; %bb.242: ; %frem.compute790
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 20
; CHECK-NEXT:    v_readlane_b32 s5, v59, 21
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:2128 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:2132 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb5b00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb5900
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb5700
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 18
; CHECK-NEXT:    v_writelane_b32 v58, s5, 19
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5200
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 20
; CHECK-NEXT:    v_writelane_b32 v58, s5, 21
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_248
; CHECK-NEXT:    s_branch .LBB0_244
; CHECK-NEXT:  .LBB0_243: ; %frem.else791
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_241
; CHECK-NEXT:  .LBB0_244: ; %frem.loop_body798
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 18
; CHECK-NEXT:    v_readlane_b32 s7, v58, 19
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5600
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5900
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5700
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 18
; CHECK-NEXT:    v_writelane_b32 v58, s7, 19
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb5600
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb5400
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb5e00
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb5c00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 22
; CHECK-NEXT:    v_writelane_b32 v58, s7, 23
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_244
; CHECK-NEXT:  ; %bb.245: ; %Flow1050
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 22
; CHECK-NEXT:    v_readlane_b32 s5, v58, 23
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.246: ; %Flow1050
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5e00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5c00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_248
; CHECK-NEXT:  .LBB0_247: ; %Flow1052
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 16
; CHECK-NEXT:    v_readlane_b32 s5, v58, 17
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2680 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2684 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_6
; CHECK-NEXT:  .LBB0_248: ; %frem.loop_exit799
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 20
; CHECK-NEXT:    v_readlane_b32 s5, v58, 21
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5b00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5200
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5100
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb4d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_247
; CHECK-NEXT:  .LBB0_249: ; %Flow1054
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 18
; CHECK-NEXT:    v_readlane_b32 s5, v59, 19
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb6100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb5f00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 24
; CHECK-NEXT:    v_writelane_b32 v58, s5, 25
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_255
; CHECK-NEXT:  ; %bb.250: ; %frem.compute821
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 16
; CHECK-NEXT:    v_readlane_b32 s5, v59, 17
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1848 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1852 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb6d00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb6b00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb6900
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 26
; CHECK-NEXT:    v_writelane_b32 v58, s5, 27
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6400
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 28
; CHECK-NEXT:    v_writelane_b32 v58, s5, 29
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_256
; CHECK-NEXT:    s_branch .LBB0_252
; CHECK-NEXT:  .LBB0_251: ; %frem.else822
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_249
; CHECK-NEXT:  .LBB0_252: ; %frem.loop_body829
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 26
; CHECK-NEXT:    v_readlane_b32 s7, v58, 27
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6800
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6b00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6900
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 26
; CHECK-NEXT:    v_writelane_b32 v58, s7, 27
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb6800
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb6600
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb7000
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb6e00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 30
; CHECK-NEXT:    v_writelane_b32 v58, s7, 31
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_252
; CHECK-NEXT:  ; %bb.253: ; %Flow1053
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 30
; CHECK-NEXT:    v_readlane_b32 s5, v58, 31
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.254: ; %Flow1053
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7000
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6e00
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6400
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_256
; CHECK-NEXT:  .LBB0_255: ; %Flow1055
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 24
; CHECK-NEXT:    v_readlane_b32 s5, v58, 25
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2400 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2404 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_5
; CHECK-NEXT:  .LBB0_256: ; %frem.loop_exit830
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 28
; CHECK-NEXT:    v_readlane_b32 s5, v58, 29
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6d00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6b00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6400
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb6300
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb5f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_255
; CHECK-NEXT:  .LBB0_257: ; %Flow1057
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 14
; CHECK-NEXT:    v_readlane_b32 s5, v59, 15
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb7300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb7100
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 32
; CHECK-NEXT:    v_writelane_b32 v58, s5, 33
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_263
; CHECK-NEXT:  ; %bb.258: ; %frem.compute852
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 12
; CHECK-NEXT:    v_readlane_b32 s5, v59, 13
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1568 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1572 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb7f00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb7d00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb7b00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 34
; CHECK-NEXT:    v_writelane_b32 v58, s5, 35
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7a00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7600
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 36
; CHECK-NEXT:    v_writelane_b32 v58, s5, 37
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_264
; CHECK-NEXT:    s_branch .LBB0_260
; CHECK-NEXT:  .LBB0_259: ; %frem.else853
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_257
; CHECK-NEXT:  .LBB0_260: ; %frem.loop_body860
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 34
; CHECK-NEXT:    v_readlane_b32 s7, v58, 35
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7a00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7d00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7b00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 34
; CHECK-NEXT:    v_writelane_b32 v58, s7, 35
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb7a00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb7800
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb8200
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb8000
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 38
; CHECK-NEXT:    v_writelane_b32 v58, s7, 39
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_260
; CHECK-NEXT:  ; %bb.261: ; %Flow1056
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 38
; CHECK-NEXT:    v_readlane_b32 s5, v58, 39
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.262: ; %Flow1056
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8200
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8000
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7600
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_264
; CHECK-NEXT:  .LBB0_263: ; %Flow1058
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 32
; CHECK-NEXT:    v_readlane_b32 s5, v58, 33
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:2120 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:2124 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_4
; CHECK-NEXT:  .LBB0_264: ; %frem.loop_exit861
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 36
; CHECK-NEXT:    v_readlane_b32 s5, v58, 37
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7f00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7d00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7b00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7600
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7500
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb7100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_263
; CHECK-NEXT:  .LBB0_265: ; %Flow1060
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 10
; CHECK-NEXT:    v_readlane_b32 s5, v59, 11
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb8500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb8300
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 40
; CHECK-NEXT:    v_writelane_b32 v58, s5, 41
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_271
; CHECK-NEXT:  ; %bb.266: ; %frem.compute883
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 8
; CHECK-NEXT:    v_readlane_b32 s5, v59, 9
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:1160 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:1164 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb9100
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb8f00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb8d00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 42
; CHECK-NEXT:    v_writelane_b32 v58, s5, 43
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8a00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8800
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 44
; CHECK-NEXT:    v_writelane_b32 v58, s5, 45
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_272
; CHECK-NEXT:    s_branch .LBB0_268
; CHECK-NEXT:  .LBB0_267: ; %frem.else884
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_265
; CHECK-NEXT:  .LBB0_268: ; %frem.loop_body891
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 42
; CHECK-NEXT:    v_readlane_b32 s7, v58, 43
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8a00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8c00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8f00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8d00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 42
; CHECK-NEXT:    v_writelane_b32 v58, s7, 43
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb8c00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb8a00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb9400
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb9200
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 46
; CHECK-NEXT:    v_writelane_b32 v58, s7, 47
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_268
; CHECK-NEXT:  ; %bb.269: ; %Flow1059
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 46
; CHECK-NEXT:    v_readlane_b32 s5, v58, 47
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.270: ; %Flow1059
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9400
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9200
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8800
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_272
; CHECK-NEXT:  .LBB0_271: ; %Flow1061
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 40
; CHECK-NEXT:    v_readlane_b32 s5, v58, 41
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8300
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1840 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1844 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_3
; CHECK-NEXT:  .LBB0_272: ; %frem.loop_exit892
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 44
; CHECK-NEXT:    v_readlane_b32 s5, v58, 45
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9100
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8f00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8d00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8800
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8700
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb8300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_271
; CHECK-NEXT:  .LBB0_273: ; %Flow1063
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 6
; CHECK-NEXT:    v_readlane_b32 s5, v59, 7
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb9700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb9500
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s4, 48
; CHECK-NEXT:    v_writelane_b32 v58, s5, 49
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_279
; CHECK-NEXT:  ; %bb.274: ; %frem.compute914
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 4
; CHECK-NEXT:    v_readlane_b32 s5, v59, 5
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:880 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:884 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xba300
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xba100
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xb9f00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 50
; CHECK-NEXT:    v_writelane_b32 v58, s5, 51
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9e00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9a00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 52
; CHECK-NEXT:    v_writelane_b32 v58, s5, 53
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_280
; CHECK-NEXT:    s_branch .LBB0_276
; CHECK-NEXT:  .LBB0_275: ; %frem.else915
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_273
; CHECK-NEXT:  .LBB0_276: ; %frem.loop_body922
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 50
; CHECK-NEXT:    v_readlane_b32 s7, v58, 51
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9c00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9e00
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba100
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9f00
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 50
; CHECK-NEXT:    v_writelane_b32 v58, s7, 51
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb9e00
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xb9c00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xba600
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xba400
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 54
; CHECK-NEXT:    v_writelane_b32 v58, s7, 55
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_276
; CHECK-NEXT:  ; %bb.277: ; %Flow1062
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 54
; CHECK-NEXT:    v_readlane_b32 s5, v58, 55
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.278: ; %Flow1062
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba600
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba400
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9a00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_280
; CHECK-NEXT:  .LBB0_279: ; %Flow1064
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 48
; CHECK-NEXT:    v_readlane_b32 s5, v58, 49
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9500
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1560 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1564 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_2
; CHECK-NEXT:  .LBB0_280: ; %frem.loop_exit923
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 52
; CHECK-NEXT:    v_readlane_b32 s5, v58, 53
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba300
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9f00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9a00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9900
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xb9500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_279
; CHECK-NEXT:  .LBB0_281: ; %Flow1066
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 2
; CHECK-NEXT:    v_readlane_b32 s5, v58, 3
; CHECK-NEXT:    s_or_saveexec_b64 s[4:5], s[4:5]
; CHECK-NEXT:    s_add_i32 s6, s32, 0xba900
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s6 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s6, s32, 0xba700
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_and_b64 s[4:5], exec, s[4:5]
; CHECK-NEXT:    ; implicit-def: $vgpr58 : SGPR spill to VGPR lane
; CHECK-NEXT:    v_writelane_b32 v58, s4, 56
; CHECK-NEXT:    v_writelane_b32 v58, s5, 57
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_xor_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_287
; CHECK-NEXT:  ; %bb.282: ; %frem.compute945
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v59, 0
; CHECK-NEXT:    v_readlane_b32 s5, v59, 1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:224 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:228 ; 4-byte Folded Reload
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v3, s[4:5]
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[0:1], s[4:5]
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[1:2], v[0:1], s4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_frexp_mant_f64_e64 v[4:5], v[6:7]
; CHECK-NEXT:    v_frexp_exp_i32_f64_e64 v0, v[6:7]
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xbb500
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s5, 1
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[4:5], s5
; CHECK-NEXT:    s_add_i32 s5, s32, 0xbb300
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_not_b32_e32 v0, v0
; CHECK-NEXT:    v_add_i32_e64 v0, s[6:7], v0, v3
; CHECK-NEXT:    s_mov_b64 s[6:7], 1.0
; CHECK-NEXT:    v_div_scale_f64 v[3:4], s[8:9], v[5:6], v[5:6], s[6:7]
; CHECK-NEXT:    v_rcp_f64_e64 v[7:8], v[3:4]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[9:10], -v[3:4], v[7:8], s[6:7]
; CHECK-NEXT:    v_fma_f64 v[7:8], v[7:8], v[9:10], v[7:8]
; CHECK-NEXT:    v_div_scale_f64 v[11:12], vcc, s[6:7], v[5:6], s[6:7]
; CHECK-NEXT:    v_mul_f64 v[9:10], v[11:12], v[7:8]
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[9:10], v[11:12]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_div_fmas_f64 v[3:4], v[3:4], v[7:8], v[9:10]
; CHECK-NEXT:    v_div_fixup_f64 v[3:4], v[3:4], v[5:6], s[6:7]
; CHECK-NEXT:    s_add_i32 s5, s32, 0xbb100
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s5 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s5 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_cmp_gt_i32_e64 s[6:7], v0, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_writelane_b32 v58, s4, 58
; CHECK-NEXT:    v_writelane_b32 v58, s5, 59
; CHECK-NEXT:    v_mov_b32_e32 v3, v0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb000
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    v_mov_b32_e32 v4, v2
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbae00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbac00
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbab00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], exec
; CHECK-NEXT:    v_writelane_b32 v58, s4, 60
; CHECK-NEXT:    v_writelane_b32 v58, s5, 61
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execz .LBB0_288
; CHECK-NEXT:    s_branch .LBB0_284
; CHECK-NEXT:  .LBB0_283: ; %frem.else946
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba900
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_281
; CHECK-NEXT:  .LBB0_284: ; %frem.loop_body953
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s6, v58, 58
; CHECK-NEXT:    v_readlane_b32 s7, v58, 59
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbae00
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb000
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb300
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb100
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f64 v[8:9], v[0:1], v[3:4]
; CHECK-NEXT:    s_mov_b32 s8, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s8
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s8, 0
; CHECK-NEXT:    s_mov_b32 s9, 0x43300000
; CHECK-NEXT:    s_mov_b32 s11, s9
; CHECK-NEXT:    s_mov_b32 s10, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v3, s11
; CHECK-NEXT:    v_bfi_b32 v3, s10, v3, v10
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 killed $sgpr8_sgpr9
; CHECK-NEXT:    v_mov_b32_e32 v11, s8
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v3
; CHECK-NEXT:    v_add_f64 v[3:4], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[3:4], v[3:4], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v7
; CHECK-NEXT:    v_fma_f64 v[3:4], -v[3:4], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[3:4], s[4:5]
; CHECK-NEXT:    v_add_f64 v[6:7], v[3:4], v[5:6]
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    v_mov_b32_e32 v8, v7
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, v8, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v6
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v4, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr3 killed $vgpr3 def $vgpr3_vgpr4 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v4, v5
; CHECK-NEXT:    s_mov_b32 s4, 26
; CHECK-NEXT:    v_ldexp_f64 v[3:4], v[3:4], s4
; CHECK-NEXT:    v_sub_i32_e64 v5, s[4:5], v2, s4
; CHECK-NEXT:    s_mov_b32 s4, 27
; CHECK-NEXT:    v_cmp_lt_i32_e64 s[4:5], v2, s4
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[6:7]
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 58
; CHECK-NEXT:    v_writelane_b32 v58, s7, 59
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbb000
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbae00
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbb800
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s6, s32, 0xbb600
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s6 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s6 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[6:7], s[4:5]
; CHECK-NEXT:    v_writelane_b32 v58, s6, 62
; CHECK-NEXT:    v_writelane_b32 v58, s7, 63
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_andn2_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_cbranch_execnz .LBB0_284
; CHECK-NEXT:  ; %bb.285: ; %Flow1065
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 62
; CHECK-NEXT:    v_readlane_b32 s5, v58, 63
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:  ; %bb.286: ; %Flow1065
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb800
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb600
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbac00
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbab00
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_288
; CHECK-NEXT:  .LBB0_287: ; %Flow1067
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 56
; CHECK-NEXT:    v_readlane_b32 s5, v58, 57
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba700
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:1152 ; 4-byte Folded Spill
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:1156 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_1
; CHECK-NEXT:  .LBB0_288: ; %frem.loop_exit954
; CHECK-NEXT:    s_or_saveexec_b64 s[56:57], -1
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[56:57]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s4, v58, 60
; CHECK-NEXT:    v_readlane_b32 s5, v58, 61
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb500
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb300
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbb100
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbac00
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s4 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_add_i32 s4, s32, 0xbab00
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_i32_e64 v7, s[4:5], v7, 25
; CHECK-NEXT:    v_ldexp_f64 v[5:6], v[5:6], v7
; CHECK-NEXT:    v_mul_f64 v[8:9], v[5:6], v[0:1]
; CHECK-NEXT:    s_mov_b32 s6, 0x432fffff
; CHECK-NEXT:    s_mov_b32 s4, -1
; CHECK-NEXT:    ; kill: def $sgpr4 killed $sgpr4 def $sgpr4_sgpr5
; CHECK-NEXT:    s_mov_b32 s5, s6
; CHECK-NEXT:    v_cmp_gt_f64_e64 s[4:5], |v[8:9]|, s[4:5]
; CHECK-NEXT:    v_mov_b32_e32 v10, v9
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b32 s7, 0x43300000
; CHECK-NEXT:    s_mov_b32 s9, s7
; CHECK-NEXT:    s_mov_b32 s8, 0x7fffffff
; CHECK-NEXT:    v_mov_b32_e32 v0, s9
; CHECK-NEXT:    v_bfi_b32 v0, s8, v0, v10
; CHECK-NEXT:    ; kill: def $sgpr6 killed $sgpr6 killed $sgpr6_sgpr7
; CHECK-NEXT:    v_mov_b32_e32 v11, s6
; CHECK-NEXT:    ; kill: def $vgpr11 killed $vgpr11 def $vgpr11_vgpr12 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v12, v0
; CHECK-NEXT:    v_add_f64 v[0:1], v[8:9], v[11:12]
; CHECK-NEXT:    v_add_f64 v[0:1], v[0:1], -v[11:12]
; CHECK-NEXT:    v_mov_b32_e32 v7, v1
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, v10, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v7
; CHECK-NEXT:    v_fma_f64 v[0:1], -v[0:1], v[3:4], v[5:6]
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    v_cmp_lt_f64_e64 s[4:5], v[0:1], s[4:5]
; CHECK-NEXT:    v_add_f64 v[4:5], v[0:1], v[3:4]
; CHECK-NEXT:    v_mov_b32_e32 v3, v1
; CHECK-NEXT:    v_mov_b32_e32 v6, v5
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, v6, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, v1, s[4:5]
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v3
; CHECK-NEXT:    v_ldexp_f64 v[0:1], v[0:1], v2
; CHECK-NEXT:    v_mov_b32_e32 v2, v1
; CHECK-NEXT:    s_mov_b32 s4, 0x7fffffff
; CHECK-NEXT:    v_and_b32_e64 v2, s4, v2
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    ; kill: def $vgpr0 killed $vgpr0 def $vgpr0_vgpr1 killed $exec
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    s_add_i32 s4, s32, 0xba700
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s4 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_branch .LBB0_287
  %A = frem <32 x double> zeroinitializer, %LGV1
  ret <32 x double> %A
}
